
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rog
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjobs/publish_scheduled.yaml
  - cronjobs/daily_email_sender.yaml
  - cronjobs/resend_data_to_pantheon.yaml
  - cronjobs/daily_prima_groups_update.yaml
  # - cronjobs/sync_consul_users.yaml
images:
  - name: rog
    newName: rg.fr-par.scw.cloud/djnd/rog
    newTag: '47db5f6b7d751de1dc70a2771bc9438431c668e2'
