
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rog-staging
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # - cronjobs/publish_scheduled.yaml
  # - cronjobs/membership_expiration_reminder.yaml
images:
  - name: rog
    newName: rg.fr-par.scw.cloud/djnd/rog-staging
    newTag: '5250c342b8fed46ac74b757e610b5d33454afafb'
