# Generated by Django 4.1.8 on 2023-04-26 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventListArchivePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("brown", "Rjava"),
                            ("light-gray", "Svetlo siva"),
                            ("dark-gray", "Temno siva"),
                            ("light-blue", "Svetlo modra"),
                            ("dark-blue", "Temno modra"),
                            ("light-green", "Svetlo zelena"),
                            ("dark-green", "Temno zelena"),
                            ("purple", "Vijolična"),
                            ("red", "Rdeča"),
                            ("orange", "Oranžna"),
                            ("pink", "Roza"),
                            ("yellow", "Rumena"),
                            ("white", "Bela"),
                        ],
                        default="light-gray",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="eventlistpage",
            name="color_scheme",
            field=models.CharField(
                choices=[
                    ("brown", "Rjava"),
                    ("light-gray", "Svetlo siva"),
                    ("dark-gray", "Temno siva"),
                    ("light-blue", "Svetlo modra"),
                    ("dark-blue", "Temno modra"),
                    ("light-green", "Svetlo zelena"),
                    ("dark-green", "Temno zelena"),
                    ("purple", "Vijolična"),
                    ("red", "Rdeča"),
                    ("orange", "Oranžna"),
                    ("pink", "Roza"),
                    ("yellow", "Rumena"),
                    ("white", "Bela"),
                ],
                default="light-gray",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="color_scheme",
            field=models.CharField(
                choices=[
                    ("brown", "Rjava"),
                    ("light-gray", "Svetlo siva"),
                    ("dark-gray", "Temno siva"),
                    ("light-blue", "Svetlo modra"),
                    ("dark-blue", "Temno modra"),
                    ("light-green", "Svetlo zelena"),
                    ("dark-green", "Temno zelena"),
                    ("purple", "Vijolična"),
                    ("red", "Rdeča"),
                    ("orange", "Oranžna"),
                    ("pink", "Roza"),
                    ("yellow", "Rumena"),
                    ("white", "Bela"),
                ],
                default="light-gray",
                max_length=20,
            ),
        ),
    ]
