# Generated by Django 4.1.8 on 2023-05-22 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_eventpage_category_alter_eventpage_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="end_day",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventpage",
            name="start_day",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
