# Generated by Django 4.1.9 on 2023-06-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_metasettings_social_media_links'),
        ('events', '0005_eventpage_end_day_eventpage_start_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
    ]
