# Generated by Django 4.1.9 on 2023-06-26 13:47

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_eventpage_thumbnail_eventpage_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='long_description',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
