# Generated by Django 4.1.9 on 2023-06-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventpage_long_description_eventpage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Kategorije dogodkov'},
        ),
        migrations.AddField(
            model_name='eventpage',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
