# Generated by Django 4.1.9 on 2023-06-28 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_workshop_delete_training_alter_tool_options_and_more"),
        ("events", "0009_alter_eventcategory_options_eventcategory_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="event_is_workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.workshop",
            ),
        ),
    ]
