# Generated by Django 4.1.9 on 2023-06-29 06:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0037_residencearchivelistpage_studioarchivelistpage"),
        ("events", "0010_eventpage_event_is_workshop"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventpage",
            options={"verbose_name": "Dogodki"},
        ),
        migrations.AddField(
            model_name="eventpage",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Arhiviraj"),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="show_see_more_section",
            field=models.BooleanField(default=False, verbose_name="Pokaži več"),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Telo"
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.eventcategory",
                verbose_name="Kategorija",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="end_day",
            field=models.DateField(verbose_name="Datum konca"),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="end_time",
            field=models.TimeField(verbose_name="Ura konca"),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="event_is_workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.workshop",
                verbose_name="Dogodek je usposabljanje",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.customimage",
                verbose_name="Slika dogodka",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="location",
            field=models.TextField(blank=True, verbose_name="Lokacija"),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Kratek opis"),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="start_day",
            field=models.DateField(verbose_name="Datum začetka"),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="start_time",
            field=models.TimeField(verbose_name="Ura začetka"),
        ),
    ]
