# Generated by Django 4.1.9 on 2023-07-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_eventlistarchivepage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcategory",
            name="color_scheme",
            field=models.CharField(
                choices=[
                    ("brown", "Rjava"),
                    ("light-gray", "Svetlo siva"),
                    ("dark-gray", "Temno siva"),
                    ("light-blue", "Svetlo modra"),
                    ("dark-blue", "Temno modra"),
                    ("light-green", "Svetlo zelena"),
                    ("dark-green", "Temno zelena"),
                    ("dark-purple", "Temno vijolična"),
                    ("light-purple", "Svetlo vijolična"),
                    ("red", "Rdeča"),
                    ("beige", "Bež"),
                    ("beige-gray", "Umazana siva"),
                    ("orange", "Oranžna"),
                    ("pink", "Roza"),
                    ("yellow", "Rumena"),
                    ("white", "Bela"),
                ],
                default="light-gray",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventlistarchivepage",
            name="color_scheme",
            field=models.CharField(
                choices=[
                    ("brown", "Rjava"),
                    ("light-gray", "Svetlo siva"),
                    ("dark-gray", "Temno siva"),
                    ("light-blue", "Svetlo modra"),
                    ("dark-blue", "Temno modra"),
                    ("light-green", "Svetlo zelena"),
                    ("dark-green", "Temno zelena"),
                    ("dark-purple", "Temno vijolična"),
                    ("light-purple", "Svetlo vijolična"),
                    ("red", "Rdeča"),
                    ("beige", "Bež"),
                    ("beige-gray", "Umazana siva"),
                    ("orange", "Oranžna"),
                    ("pink", "Roza"),
                    ("yellow", "Rumena"),
                    ("white", "Bela"),
                ],
                default="light-gray",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventlistpage",
            name="color_scheme",
            field=models.CharField(
                choices=[
                    ("brown", "Rjava"),
                    ("light-gray", "Svetlo siva"),
                    ("dark-gray", "Temno siva"),
                    ("light-blue", "Svetlo modra"),
                    ("dark-blue", "Temno modra"),
                    ("light-green", "Svetlo zelena"),
                    ("dark-green", "Temno zelena"),
                    ("dark-purple", "Temno vijolična"),
                    ("light-purple", "Svetlo vijolična"),
                    ("red", "Rdeča"),
                    ("beige", "Bež"),
                    ("beige-gray", "Umazana siva"),
                    ("orange", "Oranžna"),
                    ("pink", "Roza"),
                    ("yellow", "Rumena"),
                    ("white", "Bela"),
                ],
                default="light-gray",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="color_scheme",
            field=models.CharField(
                choices=[
                    ("brown", "Rjava"),
                    ("light-gray", "Svetlo siva"),
                    ("dark-gray", "Temno siva"),
                    ("light-blue", "Svetlo modra"),
                    ("dark-blue", "Temno modra"),
                    ("light-green", "Svetlo zelena"),
                    ("dark-green", "Temno zelena"),
                    ("dark-purple", "Temno vijolična"),
                    ("light-purple", "Svetlo vijolična"),
                    ("red", "Rdeča"),
                    ("beige", "Bež"),
                    ("beige-gray", "Umazana siva"),
                    ("orange", "Oranžna"),
                    ("pink", "Roza"),
                    ("yellow", "Rumena"),
                    ("white", "Bela"),
                ],
                default="light-gray",
                max_length=20,
            ),
        ),
    ]
