# Generated by Django 4.1.10 on 2023-08-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_alter_eventcategory_color_scheme_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="end_day",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Datum konca (če gre za večdneven dogodek)",
            ),
        ),
    ]
