# Generated by Django 4.1.10 on 2023-08-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_eventpage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='tag',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Oznaka'),
        ),
    ]
