# Generated by Django 4.1.10 on 2023-08-17 12:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_eventpage_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="body_en",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Telo"
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="body_sl",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Telo"
            ),
        ),
    ]
