# Generated by Django 4.1.10 on 2023-08-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_eventpage_body_en_eventpage_body_sl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='show_see_more_section',
            field=models.BooleanField(default=True, verbose_name='Pokaži več'),
        ),
    ]
