# Generated by Django 4.1.10 on 2023-09-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_eventpage_notice_alter_eventpage_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpage",
            name="archived",
        ),
    ]
