# Generated by Django 4.1.10 on 2023-09-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_remove_eventpage_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlistarchivepage",
            name="show_see_more_section",
            field=models.BooleanField(default=True, verbose_name="Pokaži več"),
        ),
        migrations.AddField(
            model_name="eventlistpage",
            name="show_see_more_section",
            field=models.BooleanField(default=True, verbose_name="Pokaži več"),
        ),
    ]
