# Generated by Django 4.1.11 on 2023-10-13 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_metasettings_newsletter_terms_page'),
        ('events', '0023_eventlistarchivepage_show_see_more_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlistarchivepage',
            name='meta_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Meta slika'),
        ),
        migrations.AddField(
            model_name='eventlistpage',
            name='meta_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Meta slika'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='meta_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Meta slika'),
        ),
    ]
