# Generated by Django 4.1.11 on 2023-11-23 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0025_eventpage_apply_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Ime')),
                ('surname', models.TextField(blank=True, verbose_name='Priimek')),
                ('phone', models.TextField(blank=True, verbose_name='Telefonska številka')),
                ('disabilities', models.TextField(blank=True, verbose_name='Oviranosti (naštej)')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergije (naštej)')),
                ('agreement_responsibility', models.BooleanField(default=False, verbose_name='Strinjam se z zavrnitvijo odgovornosti')),
                ('allow_photos', models.BooleanField(default=False, verbose_name='Dovoljujem fotografiranje in snemanje')),
                ('registration_finished', models.BooleanField(default=False, verbose_name='Prijava na dogodek je zaključena')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='events.eventpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prijava na dogodek',
                'verbose_name_plural': 'Dogodki - prijave',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
