# Generated by Django 4.1.11 on 2023-12-05 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_eventregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="EventRegistrationChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_name", models.TextField(verbose_name="Ime otroka")),
                ("child_surname", models.TextField(verbose_name="Priimek otroka")),
                (
                    "parent_phone",
                    models.TextField(
                        verbose_name="Telefonska številka zakonitega skrbnika"
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Datum rojstva")),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "ženski"), ("M", "moški"), ("O", "drugo")],
                        max_length=1,
                        verbose_name="Spol",
                    ),
                ),
                (
                    "gender_other",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Spol (drugo)"
                    ),
                ),
                (
                    "event_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registration_children",
                        to="events.eventregistration",
                    ),
                ),
            ],
        ),
    ]
