# Generated by Django 4.1.11 on 2023-12-05 16:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_eventregistration_sort_order_eventregistrationchild'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistrationchild',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='eventregistrationchild',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistrationchild',
            name='event_registration',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registration_children', to='events.eventregistration'),
        ),
    ]
