# Generated by Django 4.1.11 on 2023-12-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_eventpage_contact_email_eventpage_labs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='number_of_places',
            field=models.IntegerField(default=0, verbose_name='Število mest'),
        ),
    ]
