# Generated by Django 4.1.11 on 2024-02-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_eventpage_location_en_eventpage_location_sl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='pantheon_ident',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='saved_in_pantheon',
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='pantheon_ident',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Pantheon ident id'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='saved_in_pantheon',
            field=models.BooleanField(default=False, help_text='Ali event category že shranjen v Pantheon ali preprečite shranjevanje v Pantheon'),
        ),
    ]
