# Generated by Django 4.1.11 on 2024-02-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_eventpage_location_en_eventpage_location_sl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_is_for_children',
            field=models.BooleanField(default=False, help_text='Ali je dogodek namenjen otrokom'),
        ),
    ]
