# Generated by Django 4.1.11 on 2024-04-16 07:20

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0110_labpage_notice_labpage_notice_en_labpage_notice_sl_and_more'),
        ('events', '0039_remove_eventpage_pantheon_ident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='labs',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.labpage', verbose_name='Laboratoriji'),
        ),
    ]
