# Generated by Django 4.2.15 on 2025-03-11 12:11

from django.db import migrations


def migrate_categories(apps, schema_editor):
    EventPage = apps.get_model("events", "EventPage")

    event_pages = EventPage.objects.all()
    for event_page in event_pages:
        if event_page.category:
            event_page.categories.add(event_page.category)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_eventpage_categories_alter_eventpage_category'),
    ]

    operations = [
        migrations.RunPython(migrate_categories)
    ]
