# Generated by Django 4.2.15 on 2025-03-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_auto_20250311_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='category',
        ),
    ]
