# Generated by Django 4.2.15 on 2025-03-11 14:01

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_remove_eventpage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Opis kategorije, ki se pojavi nad seznamom dogodkov', null=True, verbose_name='Opis'),
        ),
    ]
