# Generated by Django 4.2.15 on 2025-03-12 14:16

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_eventcategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='event_pages', to='events.eventcategory', verbose_name='Kategorije'),
        ),
    ]
