# Generated by Django 4.2.15 on 2025-04-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_eventregistrationextraperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='allowed_extra_people',
            field=models.BooleanField(default=False, help_text='Pri prijavi na dogodek ja omogoča prijavo dodatnih oseb', verbose_name='Dovoljena prijava dodatnih oseb'),
        ),
    ]
