# Generated by Django 4.2.15 on 2025-04-09 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0056_promocode_assigned_to'),
        ('events', '0047_eventpage_allowed_extra_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='just_for_members',
            field=models.BooleanField(default=False, help_text='Za prijavo na dogodek mora biti uporabnik član', verbose_name='Dogodek samo za člane'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='required_plan',
            field=models.ForeignKey(blank=True, help_text='Za prijavo na dogodek mora uporabnik imeti aktiven ta plan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.plan', verbose_name='Zahtevan plan'),
        ),
    ]
