# Generated by Django 4.2.15 on 2025-05-14 10:00

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_eventpage_just_for_members_eventpage_required_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='additional_registration_questions',
            field=wagtail.fields.StreamField([('additional_question', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Kratko besedilo (ena vrstica)'), ('textarea', 'Besedilo (več vrstic)'), ('radio', 'Izbirno vprašanje (en odgovor)'), ('checkbox', 'Izbirno vprašanje (več odgovorov)')], 'label': 'Tip vprašanja'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Besedilo vprašanja', 'max_length': 200}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Vprašanje je obvezno', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('type', 0), ('question', 1), ('required', 2)]], {'label': 'Dodatno vprašanje'})}, default=[], null=True, verbose_name='Dodatna vprašanja ob prijavi'),
        ),
    ]
