# Generated by Django 4.2.15 on 2025-05-20 11:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_eventpage_just_for_members_eventpage_required_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='copy_extra_registration_questions_from',
            field=models.ForeignKey(blank=True, help_text='Če izberete dogodek in shranite se bodo vprašanja skopirala iz drugega dogodka in se dodala na seznam dodatnih vprašanj.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.eventpage', verbose_name='Kopiraj dodatna vprašanja iz drugega dogodka'),
        ),
        migrations.CreateModel(
            name='EventExtraRegistrationQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('question', models.CharField(max_length=200, verbose_name='Besedilo vprašanja')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Odgovor')),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='extra_registration_question_files/', verbose_name='Datoteka')),
                ('event_registration', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_registration_question_answers', to='events.eventregistration')),
            ],
            options={
                'verbose_name': 'Odgovor na dodatno vprašanje ob prijavi na dogodek',
                'verbose_name_plural': 'Odgovori na dodatna vprašanja ob prijavi na dogodek',
            },
        ),
        migrations.CreateModel(
            name='EventExtraRegistrationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('type', models.CharField(choices=[('text', 'Kratko besedilo (ena vrstica)'), ('textarea', 'Besedilo (več vrstic)'), ('radio', 'Izbirno vprašanje (en odgovor)'), ('checkboxes', 'Izbirno vprašanje (več odgovorov)'), ('file', 'Datoteka')], default='text', max_length=16, verbose_name='Tip vprašanja')),
                ('question', models.CharField(max_length=200, verbose_name='Besedilo vprašanja')),
                ('required', models.BooleanField(default=False, verbose_name='Vprašanje je obvezno')),
                ('choices', wagtail.fields.StreamField([('choice', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Opcija', 'max_length': 200})}, help_text='Izpolnite samo, če je tip vprašanja izbirno vprašanje', null=True, verbose_name='Opcije za izbirno vprašanje')),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_registration_questions', to='events.eventpage')),
            ],
            options={
                'verbose_name': 'Dodatno vprašanje ob prijavi na dogodek',
                'verbose_name_plural': 'Dodatna vprašanja ob prijavi na dogodek',
            },
        ),
    ]
