# Generated by Django 4.2.15 on 2025-05-14 10:56

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_eventpage_additional_registration_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='additional_registration_questions_answers',
            field=wagtail.fields.StreamField([('additional_question_answer', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Vprašanje', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Odgovor', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {'label': 'Odgovor na dodatno vprašanje'})}, default=[], null=True, verbose_name='Odgovori na dodatna vprašanja'),
        ),
    ]
