# Generated by Django 5.2.1 on 2025-09-02 11:11

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_eventpage_copy_extra_registration_questions_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventextraregistrationquestion',
            name='choices_en',
            field=wagtail.fields.StreamField([('choice', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Opcija', 'max_length': 200})}, help_text='Izpolnite samo, če je tip vprašanja izbirno vprašanje', null=True, verbose_name='Opcije za izbirno vprašanje'),
        ),
        migrations.AddField(
            model_name='eventextraregistrationquestion',
            name='choices_sl',
            field=wagtail.fields.StreamField([('choice', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Opcija', 'max_length': 200})}, help_text='Izpolnite samo, če je tip vprašanja izbirno vprašanje', null=True, verbose_name='Opcije za izbirno vprašanje'),
        ),
        migrations.AddField(
            model_name='eventextraregistrationquestion',
            name='question_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Besedilo vprašanja'),
        ),
        migrations.AddField(
            model_name='eventextraregistrationquestion',
            name='question_sl',
            field=models.CharField(max_length=200, null=True, verbose_name='Besedilo vprašanja'),
        ),
    ]
