# Generated by Django 5.2.1 on 2025-09-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_eventextraregistrationquestion_choices_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='agreement_responsibility',
            field=models.BooleanField(default=False, verbose_name='[NI VEČ UPORABLJENO] Strinjam se z zavrnitvijo odgovornosti'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='[NI VEČ UPORABLJENO] Alergije (naštej)'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='allow_photos',
            field=models.BooleanField(default=False, verbose_name='[NI VEČ UPORABLJENO] Dovoljujem fotografiranje in snemanje'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='disabilities',
            field=models.TextField(blank=True, verbose_name='[NI VEČ UPORABLJENO] Oviranosti (naštej)'),
        ),
    ]
