# Generated by Django 5.2.1 on 2025-09-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_alter_eventregistration_agreement_responsibility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventextraregistrationquestion',
            options={'ordering': ['sort_order'], 'verbose_name': 'Dodatno vprašanje ob prijavi na dogodek', 'verbose_name_plural': 'Dodatna vprašanja ob prijavi na dogodek'},
        ),
        migrations.AlterModelOptions(
            name='eventextraregistrationquestionanswer',
            options={'ordering': ['sort_order'], 'verbose_name': 'Odgovor na dodatno vprašanje ob prijavi na dogodek', 'verbose_name_plural': 'Odgovori na dodatna vprašanja ob prijavi na dogodek'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['sort_order'], 'verbose_name': 'Prijava na dogodek', 'verbose_name_plural': 'Dogodki - prijave'},
        ),
    ]
