# Generated by Django 4.2.15 on 2025-05-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_alter_eventpage_additional_registration_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='copy_additional_registration_questions_from',
            field=models.ForeignKey(blank=True, help_text='Če izberete dogodek in shranite se bodo vprašanja skopirala iz drugega dogodka in zamenjala obstoječa vprašanja tukaj.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.eventpage', verbose_name='Kopiraj dodatna vprašanja iz drugega dogodka'),
        ),
    ]
