# Generated by Django 5.2.1 on 2026-02-20 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_alter_eventextraregistrationquestion_options_and_more'),
        ('home', '0128_alter_contentpage_body_alter_contentpage_body_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='event_is_workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_events', to='home.workshop', verbose_name='Dogodek je usposabljanje'),
        ),
    ]
