# Generated by Django 5.2.1 on 2026-05-06 00:00

from django.db import migrations
import modelcluster.fields


def copy_event_workshop_fk_to_m2m(apps, schema_editor):
    EventPage = apps.get_model("events", "EventPage")
    through_model = EventPage.event_is_workshop.through

    through_rows = []
    events_with_workshop = EventPage.objects.exclude(
        event_is_workshop_old_id__isnull=True
    ).values_list("id", "event_is_workshop_old_id")

    for event_id, workshop_id in events_with_workshop:
        through_rows.append(
            through_model(eventpage_id=event_id, workshop_id=workshop_id)
        )

    if through_rows:
        through_model.objects.bulk_create(through_rows, ignore_conflicts=True)


def copy_event_workshop_m2m_to_fk(apps, schema_editor):
    EventPage = apps.get_model("events", "EventPage")
    through_model = EventPage.event_is_workshop.through
    first_workshop_by_event = {}

    for event_id, workshop_id in through_model.objects.order_by(
        "eventpage_id", "workshop_id"
    ).values_list("eventpage_id", "workshop_id"):
        if event_id not in first_workshop_by_event:
            first_workshop_by_event[event_id] = workshop_id

    for event in EventPage.objects.all():
        event.event_is_workshop_old_id = first_workshop_by_event.get(event.id)
        event.save(update_fields=["event_is_workshop_old"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0053_alter_eventpage_event_is_workshop"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventpage",
            old_name="event_is_workshop",
            new_name="event_is_workshop_old",
        ),
        migrations.AddField(
            model_name="eventpage",
            name="event_is_workshop",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                related_name="workshop_events",
                to="home.workshop",
                verbose_name="Dogodek je usposabljanje",
            ),
        ),
        migrations.RunPython(
            copy_event_workshop_fk_to_m2m,
            copy_event_workshop_m2m_to_fk,
        ),
        migrations.RemoveField(
            model_name="eventpage",
            name="event_is_workshop_old",
        ),
    ]
