# Generated by Django 4.2.1 on 2026-05-14 16:12
import json

from django.db import migrations


def normalize_event_is_workshop_in_revisions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    EventPage = apps.get_model("events", "EventPage")
    Revision = apps.get_model("wagtailcore", "Revision")

    event_page_content_type = ContentType.objects.get(
        app_label=EventPage._meta.app_label,
        model=EventPage._meta.model_name,
    )

    for revision in Revision.objects.all().iterator():
        content = revision.content
        content_was_string = isinstance(content, str)
        if content_was_string:
            try:
                content = json.loads(content)
            except json.JSONDecodeError:
                continue

        if not isinstance(content, dict):
            continue

        if content.get("content_type") != event_page_content_type.id:
            continue

        changed = False

        for field_name in ("categories", "labs"):
            if content.get(field_name) is None:
                content[field_name] = []
                changed = True

        event_is_workshop = content.get("event_is_workshop")
        if not isinstance(event_is_workshop, list):
            if event_is_workshop in (None, ""):
                content["event_is_workshop"] = []
            else:
                content["event_is_workshop"] = [event_is_workshop]
            changed = True

        if not changed:
            continue

        revision.content = json.dumps(content) if content_was_string else content
        revision.save(update_fields=["content"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0054_eventpage_event_is_workshop_m2m"),
    ]

    operations = [
        migrations.RunPython(
            normalize_event_is_workshop_in_revisions,
            migrations.RunPython.noop,
        ),
    ]
