# Generated by Django 4.1.8 on 2023-04-26 15:26

import django.db.models.deletion
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("news", "0002_newslistarchivepage_color_scheme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newspage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("image", wagtail.images.blocks.ImageChooserBlock())],
                null=True,
                use_json_field=False,
            ),
        ),
        migrations.AddField(
            model_name="newspage",
            name="hero_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="newslistarchivepage",
            name="color_scheme",
            field=models.CharField(
                choices=[
                    ("brown", "Rjava"),
                    ("light-gray", "Svetlo siva"),
                    ("dark-gray", "Temno siva"),
                    ("light-blue", "Svetlo modra"),
                    ("dark-blue", "Temno modra"),
                    ("light-green", "Svetlo zelena"),
                    ("dark-green", "Temno zelena"),
                    ("purple", "Vijolična"),
                    ("red", "Rdeča"),
                    ("orange", "Oranžna"),
                    ("pink", "Roza"),
                    ("yellow", "Rumena"),
                    ("white", "Bela"),
                ],
                default="light-gray",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="newslistpage",
            name="color_scheme",
            field=models.CharField(
                choices=[
                    ("brown", "Rjava"),
                    ("light-gray", "Svetlo siva"),
                    ("dark-gray", "Temno siva"),
                    ("light-blue", "Svetlo modra"),
                    ("dark-blue", "Temno modra"),
                    ("light-green", "Svetlo zelena"),
                    ("dark-green", "Temno zelena"),
                    ("purple", "Vijolična"),
                    ("red", "Rdeča"),
                    ("orange", "Oranžna"),
                    ("pink", "Roza"),
                    ("yellow", "Rumena"),
                    ("white", "Bela"),
                ],
                default="light-gray",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="color_scheme",
            field=models.CharField(
                choices=[
                    ("brown", "Rjava"),
                    ("light-gray", "Svetlo siva"),
                    ("dark-gray", "Temno siva"),
                    ("light-blue", "Svetlo modra"),
                    ("dark-blue", "Temno modra"),
                    ("light-green", "Svetlo zelena"),
                    ("dark-green", "Temno zelena"),
                    ("purple", "Vijolična"),
                    ("red", "Rdeča"),
                    ("orange", "Oranžna"),
                    ("pink", "Roza"),
                    ("yellow", "Rumena"),
                    ("white", "Bela"),
                ],
                default="light-gray",
                max_length=20,
            ),
        ),
    ]
