# Generated by Django 4.1.8 on 2023-05-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newscategory_newspage_thumbnail_newspage_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscategory',
            old_name='category_name',
            new_name='name',
        ),
    ]
