# Generated by Django 4.1.9 on 2023-06-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_metasettings_social_media_links'),
        ('news', '0006_alter_newspage_hero_image_alter_newspage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
    ]
