# Generated by Django 4.1.9 on 2023-06-29 11:17

import django.db.models.deletion
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0037_residencearchivelistpage_studioarchivelistpage"),
        ("news", "0008_alter_newscategory_options_newscategory_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspage",
            options={"verbose_name": "Novice"},
        ),
        migrations.AddField(
            model_name="newspage",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Arhiviraj"),
        ),
        migrations.AddField(
            model_name="newspage",
            name="show_see_more_section",
            field=models.BooleanField(default=False, verbose_name="Pokaži več"),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Telo"
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="news.newscategory",
                verbose_name="Kategorija",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("image", wagtail.images.blocks.ImageChooserBlock())],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Galerija",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.customimage",
                verbose_name="Naslovna slika",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Kratek opis"),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.customimage",
                verbose_name="Predogledna slika",
            ),
        ),
    ]
