# Generated by Django 4.1.10 on 2023-08-17 12:08

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_newspage_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='body_en',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Telo'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='body_sl',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Telo'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kratek opis'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='short_description_sl',
            field=models.TextField(blank=True, null=True, verbose_name='Kratek opis'),
        ),
    ]
