# Generated by Django 4.1.10 on 2023-09-01 10:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_newspage_show_see_more_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='gallery',
            field=wagtail.fields.StreamField([('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Slika')), ('image_description', wagtail.blocks.TextBlock(label='Podnapis k sliki'))]))], blank=True, null=True, use_json_field=True, verbose_name='Galerija'),
        ),
    ]
