# Generated by Django 4.1.10 on 2023-09-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_newspage_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslistarchivepage',
            name='show_see_more_section',
            field=models.BooleanField(default=True, verbose_name='Pokaži več'),
        ),
        migrations.AddField(
            model_name='newslistpage',
            name='show_see_more_section',
            field=models.BooleanField(default=True, verbose_name='Pokaži več'),
        ),
    ]
