# Generated by Django 4.1.10 on 2023-09-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0017_newslistarchivepage_show_see_more_section_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspage",
            name="archived",
        ),
        migrations.DeleteModel(
            name="NewsListArchivePage",
        ),
    ]
