# Generated by Django 4.1.11 on 2024-01-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0021_newslistpage_meta_image_newspage_meta_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="newscategory",
            name="name_en",
            field=models.TextField(null=True, verbose_name="Ime kategorije"),
        ),
        migrations.AddField(
            model_name="newscategory",
            name="name_sl",
            field=models.TextField(null=True, verbose_name="Ime kategorije"),
        ),
    ]
