# Generated by Django 4.1.8 on 2023-04-26 11:43

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("home", "0003_metasettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("brown", "Rjava"),
                            ("light-gray", "Svetlo siva"),
                            ("dark-gray", "Temno siva"),
                            ("light-blue", "Svetlo modra"),
                            ("dark-blue", "Temno modra"),
                            ("light-green", "Svetlo zelena"),
                            ("dark-green", "Temno zelena"),
                            ("purple", "Vijolična"),
                            ("red", "Rdeča"),
                            ("orange", "Oranžna"),
                            ("pink", "Roza"),
                            ("yellow", "Rumena"),
                            ("white", "Bela"),
                        ],
                        default="light-green",
                        max_length=20,
                    ),
                ),
                ("intro_text", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="LabPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("brown", "Rjava"),
                            ("light-gray", "Svetlo siva"),
                            ("dark-gray", "Temno siva"),
                            ("light-blue", "Svetlo modra"),
                            ("dark-blue", "Temno modra"),
                            ("light-green", "Svetlo zelena"),
                            ("dark-green", "Temno zelena"),
                            ("purple", "Vijolična"),
                            ("red", "Rdeča"),
                            ("orange", "Oranžna"),
                            ("pink", "Roza"),
                            ("yellow", "Rumena"),
                            ("white", "Bela"),
                        ],
                        default="light-green",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=12)),
                ("link_1", models.URLField(blank=True)),
                ("link_2", models.URLField(blank=True)),
                ("link_3", models.URLField(blank=True)),
                ("contact_description", models.TextField(blank=True)),
                (
                    "working_hours",
                    wagtail.fields.StreamField(
                        [
                            (
                                "time",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("day", wagtail.blocks.CharBlock(label="Dan")),
                                        (
                                            "start_time",
                                            wagtail.blocks.TimeBlock(
                                                label="Začetna ura"
                                            ),
                                        ),
                                        (
                                            "end_time",
                                            wagtail.blocks.TimeBlock(
                                                label="Končna ura"
                                            ),
                                        ),
                                    ],
                                    label="Dan in ura",
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="LibraryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("brown", "Rjava"),
                            ("light-gray", "Svetlo siva"),
                            ("dark-gray", "Temno siva"),
                            ("light-blue", "Svetlo modra"),
                            ("dark-blue", "Temno modra"),
                            ("light-green", "Svetlo zelena"),
                            ("dark-green", "Temno zelena"),
                            ("purple", "Vijolična"),
                            ("red", "Rdeča"),
                            ("orange", "Oranžna"),
                            ("pink", "Roza"),
                            ("yellow", "Rumena"),
                            ("white", "Bela"),
                        ],
                        default="pink",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=12)),
                ("link_1", models.URLField(blank=True)),
                ("link_2", models.URLField(blank=True)),
                ("link_3", models.URLField(blank=True)),
                ("contact_description", models.TextField(blank=True)),
                (
                    "working_hours",
                    wagtail.fields.StreamField(
                        [
                            (
                                "time",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("day", wagtail.blocks.CharBlock(label="Dan")),
                                        (
                                            "start_time",
                                            wagtail.blocks.TimeBlock(
                                                label="Začetna ura"
                                            ),
                                        ),
                                        (
                                            "end_time",
                                            wagtail.blocks.TimeBlock(
                                                label="Končna ura"
                                            ),
                                        ),
                                    ],
                                    label="Dan in ura",
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="MarketStoreListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("brown", "Rjava"),
                            ("light-gray", "Svetlo siva"),
                            ("dark-gray", "Temno siva"),
                            ("light-blue", "Svetlo modra"),
                            ("dark-blue", "Temno modra"),
                            ("light-green", "Svetlo zelena"),
                            ("dark-green", "Temno zelena"),
                            ("purple", "Vijolična"),
                            ("red", "Rdeča"),
                            ("orange", "Oranžna"),
                            ("pink", "Roza"),
                            ("yellow", "Rumena"),
                            ("white", "Bela"),
                        ],
                        default="brown",
                        max_length=20,
                    ),
                ),
                ("intro_text", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="MarketStorePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("brown", "Rjava"),
                            ("light-gray", "Svetlo siva"),
                            ("dark-gray", "Temno siva"),
                            ("light-blue", "Svetlo modra"),
                            ("dark-blue", "Temno modra"),
                            ("light-green", "Svetlo zelena"),
                            ("dark-green", "Temno zelena"),
                            ("purple", "Vijolična"),
                            ("red", "Rdeča"),
                            ("orange", "Oranžna"),
                            ("pink", "Roza"),
                            ("yellow", "Rumena"),
                            ("white", "Bela"),
                        ],
                        default="brown",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=12)),
                ("link_1", models.URLField(blank=True)),
                ("link_2", models.URLField(blank=True)),
                ("link_3", models.URLField(blank=True)),
                ("contact_description", models.TextField(blank=True)),
                (
                    "working_hours",
                    wagtail.fields.StreamField(
                        [
                            (
                                "time",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("day", wagtail.blocks.CharBlock(label="Dan")),
                                        (
                                            "start_time",
                                            wagtail.blocks.TimeBlock(
                                                label="Začetna ura"
                                            ),
                                        ),
                                        (
                                            "end_time",
                                            wagtail.blocks.TimeBlock(
                                                label="Končna ura"
                                            ),
                                        ),
                                    ],
                                    label="Dan in ura",
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ResidenceListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("brown", "Rjava"),
                            ("light-gray", "Svetlo siva"),
                            ("dark-gray", "Temno siva"),
                            ("light-blue", "Svetlo modra"),
                            ("dark-blue", "Temno modra"),
                            ("light-green", "Svetlo zelena"),
                            ("dark-green", "Temno zelena"),
                            ("purple", "Vijolična"),
                            ("red", "Rdeča"),
                            ("orange", "Oranžna"),
                            ("pink", "Roza"),
                            ("yellow", "Rumena"),
                            ("white", "Bela"),
                        ],
                        default="dark-gray",
                        max_length=20,
                    ),
                ),
                ("intro_text", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ResidencePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("brown", "Rjava"),
                            ("light-gray", "Svetlo siva"),
                            ("dark-gray", "Temno siva"),
                            ("light-blue", "Svetlo modra"),
                            ("dark-blue", "Temno modra"),
                            ("light-green", "Svetlo zelena"),
                            ("dark-green", "Temno zelena"),
                            ("purple", "Vijolična"),
                            ("red", "Rdeča"),
                            ("orange", "Oranžna"),
                            ("pink", "Roza"),
                            ("yellow", "Rumena"),
                            ("white", "Bela"),
                        ],
                        default="dark-gray",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=12)),
                ("link_1", models.URLField(blank=True)),
                ("link_2", models.URLField(blank=True)),
                ("link_3", models.URLField(blank=True)),
                ("contact_description", models.TextField(blank=True)),
                (
                    "working_hours",
                    wagtail.fields.StreamField(
                        [
                            (
                                "time",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("day", wagtail.blocks.CharBlock(label="Dan")),
                                        (
                                            "start_time",
                                            wagtail.blocks.TimeBlock(
                                                label="Začetna ura"
                                            ),
                                        ),
                                        (
                                            "end_time",
                                            wagtail.blocks.TimeBlock(
                                                label="Končna ura"
                                            ),
                                        ),
                                    ],
                                    label="Dan in ura",
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="StudioListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("brown", "Rjava"),
                            ("light-gray", "Svetlo siva"),
                            ("dark-gray", "Temno siva"),
                            ("light-blue", "Svetlo modra"),
                            ("dark-blue", "Temno modra"),
                            ("light-green", "Svetlo zelena"),
                            ("dark-green", "Temno zelena"),
                            ("purple", "Vijolična"),
                            ("red", "Rdeča"),
                            ("orange", "Oranžna"),
                            ("pink", "Roza"),
                            ("yellow", "Rumena"),
                            ("white", "Bela"),
                        ],
                        default="yellow",
                        max_length=20,
                    ),
                ),
                ("intro_text", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="StudioPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("brown", "Rjava"),
                            ("light-gray", "Svetlo siva"),
                            ("dark-gray", "Temno siva"),
                            ("light-blue", "Svetlo modra"),
                            ("dark-blue", "Temno modra"),
                            ("light-green", "Svetlo zelena"),
                            ("dark-green", "Temno zelena"),
                            ("purple", "Vijolična"),
                            ("red", "Rdeča"),
                            ("orange", "Oranžna"),
                            ("pink", "Roza"),
                            ("yellow", "Rumena"),
                            ("white", "Bela"),
                        ],
                        default="yellow",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=12)),
                ("link_1", models.URLField(blank=True)),
                ("link_2", models.URLField(blank=True)),
                ("link_3", models.URLField(blank=True)),
                ("contact_description", models.TextField(blank=True)),
                (
                    "working_hours",
                    wagtail.fields.StreamField(
                        [
                            (
                                "time",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("day", wagtail.blocks.CharBlock(label="Dan")),
                                        (
                                            "start_time",
                                            wagtail.blocks.TimeBlock(
                                                label="Začetna ura"
                                            ),
                                        ),
                                        (
                                            "end_time",
                                            wagtail.blocks.TimeBlock(
                                                label="Končna ura"
                                            ),
                                        ),
                                    ],
                                    label="Dan in ura",
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
