# Generated by Django 4.1.8 on 2023-04-24 09:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0003_metasettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('color_scheme', models.CharField(choices=[('brown', 'Rjava'), ('light-gray', 'Svetlo siva'), ('dark-gray', 'Temno siva'), ('light-blue', 'Svetlo modra'), ('dark-blue', 'Temno modra'), ('light-green', 'Svetlo zelena'), ('dark-green', 'Temno zelena'), ('purple', 'Vijolična'), ('red', 'Rdeča'), ('orange', 'Oranžna'), ('pink', 'Roza'), ('yellow', 'Rumena'), ('white', 'Bela')], default='white', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('body', wagtail.blocks.StreamBlock([('box_emphasized', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Naslov')), ('text', wagtail.blocks.RichTextBlock(label='Besedilo', required=False)), ('buttons', wagtail.blocks.StreamBlock([('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock('Besedilo na gumbu')), ('page', wagtail.blocks.PageChooserBlock(label='Stran', required=False))], label='Gumb'))], label='Gumbi', required=False))], icon='title', label='Poudarjeno besedilo z okvirjem', template='home/blocks/box_emphasized.html')), ('news_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Naslov')), ('news', wagtail.blocks.StreamBlock([('news_page', wagtail.blocks.PageChooserBlock(label='Stran', page_type=['news.NewsPage'], required=False))], label='Novice'))], icon='title', label='Izpostavljene novice', template='home/blocks/news_section.html')), ('image_embed', wagtail.images.blocks.ImageChooserBlock(label='Slika', template='home/blocks/image_embed.html'))], label='Vsebina', required=False))]))], default='', use_json_field=False, verbose_name='Telo'),
        ),
        migrations.CreateModel(
            name='ObjectListPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basepage')),
                ('intro_text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('home.basepage',),
        ),
        migrations.CreateModel(
            name='ObjectProfilePage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basepage')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('home.basepage',),
        ),
        migrations.CreateModel(
            name='LibraryPage',
            fields=[
                ('objectprofilepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.objectprofilepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.objectprofilepage',),
        ),
        migrations.CreateModel(
            name='MarketStorePage',
            fields=[
                ('objectprofilepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.objectprofilepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.objectprofilepage',),
        ),
        migrations.CreateModel(
            name='ResidencePage',
            fields=[
                ('objectprofilepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.objectprofilepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.objectprofilepage',),
        ),
        migrations.CreateModel(
            name='StudioPage',
            fields=[
                ('objectprofilepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.objectprofilepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.objectprofilepage',),
        ),
    ]
