# Generated by Django 4.1.8 on 2023-05-03 12:31

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("home", "0004_lablistpage_labpage_librarypage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("brown", "Rjava"),
                            ("light-gray", "Svetlo siva"),
                            ("dark-gray", "Temno siva"),
                            ("light-blue", "Svetlo modra"),
                            ("dark-blue", "Temno modra"),
                            ("light-green", "Svetlo zelena"),
                            ("dark-green", "Temno zelena"),
                            ("purple", "Vijolična"),
                            ("red", "Rdeča"),
                            ("orange", "Oranžna"),
                            ("pink", "Roza"),
                            ("yellow", "Rumena"),
                            ("white", "Bela"),
                        ],
                        default="white",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
