# Generated by Django 4.1.8 on 2023-04-25 08:59

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactinformation_objectprofilepage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectprofilepage',
            name='contact_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='objectprofilepage',
            name='link_1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='objectprofilepage',
            name='link_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='objectprofilepage',
            name='link_3',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='objectprofilepage',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='objectprofilepage',
            name='working_hours',
            field=wagtail.fields.StreamField([('day', wagtail.blocks.CharBlock(form_classname='Dan')), ('start_time', wagtail.blocks.TimeBlock(form_classname='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(form_classname='Končna ura'))], blank=True, use_json_field=None),
        ),
    ]
