# Generated by Django 4.1.8 on 2023-04-28 10:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contentpage_color_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('box_emphasized', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Naslov')), ('text', wagtail.blocks.RichTextBlock(label='Besedilo', required=False)), ('buttons', wagtail.blocks.StreamBlock([('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock('Besedilo na gumbu')), ('page', wagtail.blocks.PageChooserBlock(label='Stran', required=False))], label='Gumb'))], label='Gumbi', required=False))], icon='title', label='Poudarjeno besedilo z okvirjem', template='home/blocks/box_emphasized.html')), ('news_section', wagtail.blocks.StructBlock([('color', wagtail.blocks.ChoiceBlock(choices=[('brown', 'Rjava'), ('light-gray', 'Svetlo siva'), ('dark-gray', 'Temno siva'), ('light-blue', 'Svetlo modra'), ('dark-blue', 'Temno modra'), ('light-green', 'Svetlo zelena'), ('dark-green', 'Temno zelena'), ('purple', 'Vijolična'), ('red', 'Rdeča'), ('orange', 'Oranžna'), ('pink', 'Roza'), ('yellow', 'Rumena'), ('white', 'Bela')], label='Barva')), ('title', wagtail.blocks.CharBlock(label='Naslov')), ('news', wagtail.blocks.StreamBlock([('news_page', wagtail.blocks.PageChooserBlock(label='Stran', page_type=['news.NewsPage'], required=False))], label='Novice'))], icon='title', label='Izpostavljene novice', template='home/blocks/news_section.html')), ('image_embed', wagtail.images.blocks.ImageChooserBlock(label='Slika', template='home/blocks/image_embed.html'))], null=True, use_json_field=False, verbose_name='Telo'),
        ),
    ]
