# Generated by Django 4.1.8 on 2023-05-03 12:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0005_contentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('bulletin_board', wagtail.blocks.StructBlock([('title', wagtail.blocks.TextBlock(label='Naslov')), ('notice', wagtail.blocks.TextBlock(label='Obvestilo'))])), ('news_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Naslov modula')), ('exposed_news', wagtail.blocks.StreamBlock([('news_page', wagtail.blocks.PageChooserBlock(label='Novica', page_type=['news.NewsPage']))]))])), (
                'events_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Naslov modula')), ('exposed_events', wagtail.blocks.StreamBlock([('event', wagtail.blocks.PageChooserBlock(label='Dogodek', page_type=['events.EventPage']))]))])), ('image_embed', wagtail.images.blocks.ImageChooserBlock(label='Slika', template='home/blocks/image_embed.html'))], null=True, use_json_field=False, verbose_name='Telo'),
        ),
    ]
