# Generated by Django 4.1.8 on 2023-04-25 09:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_objectprofilepage_contact_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectprofilepage',
            name='working_hours',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura'))], use_json_field=False),
        ),
    ]
