# Generated by Django 4.1.7 on 2023-03-01 13:14

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StreamBlock([('body', wagtail.blocks.StreamBlock([], required=False))]))], default='', use_json_field=False, verbose_name='Barvna sekcija'),
        ),
    ]
