# Generated by Django 4.1.8 on 2023-04-26 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_studiolistpage_delete_contactinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStoreListPage',
            fields=[
                ('objectlistpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.objectlistpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.objectlistpage',),
        ),
        migrations.CreateModel(
            name='ResidenceListPage',
            fields=[
                ('objectlistpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.objectlistpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.objectlistpage',),
        ),
        migrations.AlterField(
            model_name='objectlistpage',
            name='color_scheme',
            field=models.CharField(choices=[('brown', 'Rjava'), ('light-gray', 'Svetlo siva'), ('dark-gray', 'Temno siva'), ('light-blue', 'Svetlo modra'), ('dark-blue', 'Temno modra'), ('light-green', 'Svetlo zelena'), ('dark-green', 'Temno zelena'), ('purple', 'Vijolična'), ('red', 'Rdeča'), ('orange', 'Oranžna'), ('pink', 'Roza'), ('yellow', 'Rumena'), ('white', 'Bela')], default='dark-gray', max_length=20),
        ),
    ]
