# Generated by Django 4.1.9 on 2023-06-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_hero_image_labpage_image_librarypage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labpage',
            name='thumbnail_animation',
        ),
    ]
