# Generated by Django 4.1.9 on 2023-06-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailmedia", "0004_duration_optional_floatfield"),
        ("home", "0015_remove_labpage_thumbnail_animation"),
    ]

    operations = [
        migrations.AddField(
            model_name="labpage",
            name="thumbnail_animation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailmedia.media",
            ),
        ),
    ]
