# Generated by Django 4.1.9 on 2023-06-20 08:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_labpage_thumbnail_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasettings',
            name='footer_links',
            field=wagtail.fields.StreamField([('page_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Če je prazno, se uporabi naslov strani.', label='Ime', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Stran'))])), ('external_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(label='Ime')), ('url', wagtail.blocks.URLBlock(label='URL'))]))], blank=True, use_json_field=True, verbose_name='Povezave v nogi'),
        ),
        migrations.AlterField(
            model_name='metasettings',
            name='header_links',
            field=wagtail.fields.StreamField([('page_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Če je prazno, se uporabi naslov strani.', label='Ime', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Stran'))])), ('external_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(label='Ime')), ('url', wagtail.blocks.URLBlock(label='URL'))]))], blank=True, use_json_field=True, verbose_name='Povezave v navigacijski vrstici'),
        ),
    ]
