# Generated by Django 4.1.9 on 2023-06-21 04:49

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_metasettings_organization_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasettings',
            name='footer_images',
            field=wagtail.fields.StreamField([('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.blocks.CharBlock(label='Naslov'))]))], blank=True, use_json_field=True, verbose_name='Slike'),
        ),
    ]
