# Generated by Django 4.1.9 on 2023-06-21 05:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_metasettings_footer_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasettings',
            name='footer_images',
            field=wagtail.fields.StreamField([('logo', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.blocks.CharBlock(blank=True, label='Naslov'))]))], blank=True, use_json_field=True, verbose_name='Logotipi'),
        ),
    ]
