# Generated by Django 4.1.9 on 2023-06-21 06:16

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_alter_metasettings_footer_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="metasettings",
            name="social_media_facebook",
            field=models.URLField(blank=True, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="social_media_instagram",
            field=models.URLField(blank=True, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="social_media_twitter",
            field=models.URLField(blank=True, verbose_name="Twitter"),
        ),
        migrations.AlterField(
            model_name="metasettings",
            name="footer_images",
            field=wagtail.fields.StreamField(
                [
                    (
                        "logo",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "description",
                                    wagtail.blocks.CharBlock(
                                        blank=True, label="Naslov", required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Logotipi",
            ),
        ),
    ]
