# Generated by Django 4.1.9 on 2023-06-22 08:08

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_customimage_customrendition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metasettings",
            name="social_media_facebook",
        ),
        migrations.RemoveField(
            model_name="metasettings",
            name="social_media_instagram",
        ),
        migrations.RemoveField(
            model_name="metasettings",
            name="social_media_twitter",
        ),
        migrations.AddField(
            model_name="metasettings",
            name="social_media_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "page_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(
                                        help_text="Če je prazno, se uporabi naslov strani.",
                                        label="Ime",
                                        required=False,
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(label="Stran"),
                                ),
                            ]
                        ),
                    ),
                    (
                        "external_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock(label="Ime")),
                                ("url", wagtail.blocks.URLBlock(label="URL")),
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Družbena omrežja",
            ),
        ),
    ]
