# Generated by Django 4.1.9 on 2023-06-22 08:14

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_metasettings_social_media_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasettings',
            name='social_media_links',
            field=wagtail.fields.StreamField([('page_link', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Če je prazno, se uporabi naslov strani.', label='Ime', required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Stran'))]))], blank=True, use_json_field=True, verbose_name='Družbena omrežja'),
        ),
    ]
