# Generated by Django 4.1.9 on 2023-06-22 08:15

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_alter_metasettings_social_media_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metasettings",
            name="social_media_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "external_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock(label="Ime")),
                                ("url", wagtail.blocks.URLBlock(label="URL")),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Družbena omrežja",
            ),
        ),
    ]
