# Generated by Django 4.1.9 on 2023-06-27 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_tool_training_toolspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
        migrations.AlterField(
            model_name='labpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
        migrations.AlterField(
            model_name='librarypage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
        migrations.AlterField(
            model_name='marketstorepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
        migrations.AlterField(
            model_name='residencepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
        migrations.AlterField(
            model_name='studiopage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
        migrations.AlterField(
            model_name='studiopage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage'),
        ),
    ]
