# Generated by Django 4.1.9 on 2023-06-28 17:39

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_workshop_delete_training_alter_tool_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labpage",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Arhiviraj"),
        ),
        migrations.AddField(
            model_name="labpage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("image", wagtail.images.blocks.ImageChooserBlock(label="Slika"))],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Galerija",
            ),
        ),
        migrations.AddField(
            model_name="librarypage",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Arhiviraj"),
        ),
        migrations.AddField(
            model_name="librarypage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("image", wagtail.images.blocks.ImageChooserBlock(label="Slika"))],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Galerija",
            ),
        ),
        migrations.AddField(
            model_name="marketstorepage",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Arhiviraj"),
        ),
        migrations.AddField(
            model_name="marketstorepage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("image", wagtail.images.blocks.ImageChooserBlock(label="Slika"))],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Galerija",
            ),
        ),
        migrations.AddField(
            model_name="residencepage",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Arhiviraj"),
        ),
        migrations.AddField(
            model_name="residencepage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("image", wagtail.images.blocks.ImageChooserBlock(label="Slika"))],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Galerija",
            ),
        ),
        migrations.AddField(
            model_name="studiopage",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Arhiviraj"),
        ),
        migrations.AddField(
            model_name="studiopage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("image", wagtail.images.blocks.ImageChooserBlock(label="Slika"))],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Galerija",
            ),
        ),
        migrations.AlterField(
            model_name="labpage",
            name="contact_description",
            field=models.TextField(blank=True, verbose_name="Dodatna informacija"),
        ),
        migrations.AlterField(
            model_name="labpage",
            name="description",
            field=models.TextField(blank=True, verbose_name="Opis"),
        ),
        migrations.AlterField(
            model_name="labpage",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Elektronski naslov"
            ),
        ),
        migrations.AlterField(
            model_name="labpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.customimage",
                verbose_name="Slika",
            ),
        ),
        migrations.AlterField(
            model_name="labpage",
            name="link_1",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="labpage",
            name="link_2",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="labpage",
            name="link_3",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="labpage",
            name="phone",
            field=models.CharField(
                blank=True, max_length=12, verbose_name="Telefonska številka"
            ),
        ),
        migrations.AlterField(
            model_name="labpage",
            name="working_hours",
            field=wagtail.fields.StreamField(
                [
                    (
                        "time",
                        wagtail.blocks.StructBlock(
                            [
                                ("day", wagtail.blocks.CharBlock(label="Dan")),
                                (
                                    "start_time",
                                    wagtail.blocks.TimeBlock(label="Začetna ura"),
                                ),
                                (
                                    "end_time",
                                    wagtail.blocks.TimeBlock(label="Končna ura"),
                                ),
                            ],
                            label="Dan in ura",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Delovni čas",
            ),
        ),
        migrations.AlterField(
            model_name="librarypage",
            name="contact_description",
            field=models.TextField(blank=True, verbose_name="Dodatna informacija"),
        ),
        migrations.AlterField(
            model_name="librarypage",
            name="description",
            field=models.TextField(blank=True, verbose_name="Opis"),
        ),
        migrations.AlterField(
            model_name="librarypage",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Elektronski naslov"
            ),
        ),
        migrations.AlterField(
            model_name="librarypage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.customimage",
                verbose_name="Slika",
            ),
        ),
        migrations.AlterField(
            model_name="librarypage",
            name="link_1",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="librarypage",
            name="link_2",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="librarypage",
            name="link_3",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="librarypage",
            name="phone",
            field=models.CharField(
                blank=True, max_length=12, verbose_name="Telefonska številka"
            ),
        ),
        migrations.AlterField(
            model_name="librarypage",
            name="working_hours",
            field=wagtail.fields.StreamField(
                [
                    (
                        "time",
                        wagtail.blocks.StructBlock(
                            [
                                ("day", wagtail.blocks.CharBlock(label="Dan")),
                                (
                                    "start_time",
                                    wagtail.blocks.TimeBlock(label="Začetna ura"),
                                ),
                                (
                                    "end_time",
                                    wagtail.blocks.TimeBlock(label="Končna ura"),
                                ),
                            ],
                            label="Dan in ura",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Delovni čas",
            ),
        ),
        migrations.AlterField(
            model_name="marketstorepage",
            name="contact_description",
            field=models.TextField(blank=True, verbose_name="Dodatna informacija"),
        ),
        migrations.AlterField(
            model_name="marketstorepage",
            name="description",
            field=models.TextField(blank=True, verbose_name="Opis"),
        ),
        migrations.AlterField(
            model_name="marketstorepage",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Elektronski naslov"
            ),
        ),
        migrations.AlterField(
            model_name="marketstorepage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.customimage",
                verbose_name="Slika",
            ),
        ),
        migrations.AlterField(
            model_name="marketstorepage",
            name="link_1",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="marketstorepage",
            name="link_2",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="marketstorepage",
            name="link_3",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="marketstorepage",
            name="phone",
            field=models.CharField(
                blank=True, max_length=12, verbose_name="Telefonska številka"
            ),
        ),
        migrations.AlterField(
            model_name="marketstorepage",
            name="working_hours",
            field=wagtail.fields.StreamField(
                [
                    (
                        "time",
                        wagtail.blocks.StructBlock(
                            [
                                ("day", wagtail.blocks.CharBlock(label="Dan")),
                                (
                                    "start_time",
                                    wagtail.blocks.TimeBlock(label="Začetna ura"),
                                ),
                                (
                                    "end_time",
                                    wagtail.blocks.TimeBlock(label="Končna ura"),
                                ),
                            ],
                            label="Dan in ura",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Delovni čas",
            ),
        ),
        migrations.AlterField(
            model_name="residencepage",
            name="contact_description",
            field=models.TextField(blank=True, verbose_name="Dodatna informacija"),
        ),
        migrations.AlterField(
            model_name="residencepage",
            name="description",
            field=models.TextField(blank=True, verbose_name="Opis"),
        ),
        migrations.AlterField(
            model_name="residencepage",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Elektronski naslov"
            ),
        ),
        migrations.AlterField(
            model_name="residencepage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.customimage",
                verbose_name="Slika",
            ),
        ),
        migrations.AlterField(
            model_name="residencepage",
            name="link_1",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="residencepage",
            name="link_2",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="residencepage",
            name="link_3",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="residencepage",
            name="phone",
            field=models.CharField(
                blank=True, max_length=12, verbose_name="Telefonska številka"
            ),
        ),
        migrations.AlterField(
            model_name="residencepage",
            name="working_hours",
            field=wagtail.fields.StreamField(
                [
                    (
                        "time",
                        wagtail.blocks.StructBlock(
                            [
                                ("day", wagtail.blocks.CharBlock(label="Dan")),
                                (
                                    "start_time",
                                    wagtail.blocks.TimeBlock(label="Začetna ura"),
                                ),
                                (
                                    "end_time",
                                    wagtail.blocks.TimeBlock(label="Končna ura"),
                                ),
                            ],
                            label="Dan in ura",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Delovni čas",
            ),
        ),
        migrations.AlterField(
            model_name="studiopage",
            name="contact_description",
            field=models.TextField(blank=True, verbose_name="Dodatna informacija"),
        ),
        migrations.AlterField(
            model_name="studiopage",
            name="description",
            field=models.TextField(blank=True, verbose_name="Opis"),
        ),
        migrations.AlterField(
            model_name="studiopage",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Elektronski naslov"
            ),
        ),
        migrations.AlterField(
            model_name="studiopage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.customimage",
                verbose_name="Slika",
            ),
        ),
        migrations.AlterField(
            model_name="studiopage",
            name="link_1",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="studiopage",
            name="link_2",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="studiopage",
            name="link_3",
            field=models.URLField(blank=True, verbose_name="Povezava"),
        ),
        migrations.AlterField(
            model_name="studiopage",
            name="phone",
            field=models.CharField(
                blank=True, max_length=12, verbose_name="Telefonska številka"
            ),
        ),
        migrations.AlterField(
            model_name="studiopage",
            name="working_hours",
            field=wagtail.fields.StreamField(
                [
                    (
                        "time",
                        wagtail.blocks.StructBlock(
                            [
                                ("day", wagtail.blocks.CharBlock(label="Dan")),
                                (
                                    "start_time",
                                    wagtail.blocks.TimeBlock(label="Začetna ura"),
                                ),
                                (
                                    "end_time",
                                    wagtail.blocks.TimeBlock(label="Končna ura"),
                                ),
                            ],
                            label="Dan in ura",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Delovni čas",
            ),
        ),
    ]
