# Generated by Django 4.1.9 on 2023-06-29 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("home", "0036_labpage_show_see_more_section_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResidenceArchiveListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("brown", "Rjava"),
                            ("light-gray", "Svetlo siva"),
                            ("dark-gray", "Temno siva"),
                            ("light-blue", "Svetlo modra"),
                            ("dark-blue", "Temno modra"),
                            ("light-green", "Svetlo zelena"),
                            ("dark-green", "Temno zelena"),
                            ("purple", "Vijolična"),
                            ("red", "Rdeča"),
                            ("orange", "Oranžna"),
                            ("pink", "Roza"),
                            ("yellow", "Rumena"),
                            ("white", "Bela"),
                        ],
                        default="dark-gray",
                        max_length=20,
                    ),
                ),
                ("show_see_more_section", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="StudioArchiveListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("brown", "Rjava"),
                            ("light-gray", "Svetlo siva"),
                            ("dark-gray", "Temno siva"),
                            ("light-blue", "Svetlo modra"),
                            ("dark-blue", "Temno modra"),
                            ("light-green", "Svetlo zelena"),
                            ("dark-green", "Temno zelena"),
                            ("purple", "Vijolična"),
                            ("red", "Rdeča"),
                            ("orange", "Oranžna"),
                            ("pink", "Roza"),
                            ("yellow", "Rumena"),
                            ("white", "Bela"),
                        ],
                        default="yellow",
                        max_length=20,
                    ),
                ),
                ("show_see_more_section", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
