# Generated by Django 4.1.9 on 2023-06-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0037_residencearchivelistpage_studioarchivelistpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="metasettings",
            name="header_marquee",
            field=models.TextField(
                blank=True, null=True, verbose_name="Vrteče besedilo"
            ),
        ),
    ]
