# Generated by Django 4.1.9 on 2023-06-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0038_metasettings_header_marquee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studiopage",
            options={"verbose_name": "Studio", "verbose_name_plural": "Studii"},
        ),
    ]
