# Generated by Django 4.1.9 on 2023-07-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('home', '0044_alter_metasettings_organization_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketstorepage',
            name='card_color_scheme',
            field=models.CharField(choices=[('brown', 'Rjava'), ('light-gray', 'Svetlo siva'), ('dark-gray', 'Temno siva'), ('light-blue', 'Svetlo modra'), ('dark-blue', 'Temno modra'), ('light-green', 'Svetlo zelena'), ('dark-green', 'Temno zelena'), ('purple', 'Vijolična'), ('red', 'Rdeča'), ('orange', 'Oranžna'), ('pink', 'Roza'), ('yellow', 'Rumena'), ('white', 'Bela')], default='white', max_length=20, verbose_name='Barvna shema kartice na seznamu'),
        ),
        migrations.AlterField(
            model_name='lablistpage',
            name='show_see_more_section',
            field=models.BooleanField(default=False, verbose_name="Dodaj sekcijo 'Poglej več'"),
        ),
        migrations.AlterField(
            model_name='labpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Predogledna slika'),
        ),
        migrations.AlterField(
            model_name='labpage',
            name='thumbnail_animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Animacija predogledne slike'),
        ),
        migrations.AlterField(
            model_name='marketstorelistpage',
            name='show_see_more_section',
            field=models.BooleanField(default=False, verbose_name="Dodaj sekcijo 'Poglej več'"),
        ),
        migrations.AlterField(
            model_name='residencelistpage',
            name='show_see_more_section',
            field=models.BooleanField(default=False, verbose_name="Dodaj sekcijo 'Poglej več'"),
        ),
        migrations.AlterField(
            model_name='studiolistpage',
            name='show_see_more_section',
            field=models.BooleanField(default=False, verbose_name="Dodaj sekcijo 'Poglej več'"),
        ),
        migrations.AlterField(
            model_name='studiopage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Predogledna slika'),
        ),
    ]
