# Generated by Django 4.1.9 on 2023-07-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0057_alter_contentpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="secondary_navigation",
            field=models.BooleanField(default=False, verbose_name="Sekundarni meni"),
        ),
    ]
