# Generated by Django 4.1.10 on 2023-08-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0063_contentpage_body_en_contentpage_body_sl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studiolistpage",
            name="intro_text_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studiolistpage",
            name="intro_text_sl",
            field=models.TextField(blank=True, null=True),
        ),
    ]
