# Generated by Django 4.1.10 on 2023-08-18 09:15

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_labpage_contact_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basictextpage',
            name='body_en',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Telo'),
        ),
        migrations.AddField(
            model_name='basictextpage',
            name='body_sl',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Telo'),
        ),
    ]
