# Generated by Django 4.1.10 on 2023-08-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0071_alter_contentpage_body_alter_contentpage_body_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="more_information_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Povezava za več informacij"
            ),
        ),
    ]
