# Generated by Django 4.1.10 on 2023-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_remove_labpage_link_1_remove_labpage_link_1_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpage',
            name='contact_description',
            field=models.TextField(blank=True, max_length=50, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='labpage',
            name='contact_description_en',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='labpage',
            name='contact_description_sl',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='labpage',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='labpage',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='labpage',
            name='website',
            field=models.URLField(blank=True, verbose_name='Spletna stran'),
        ),
        migrations.AlterField(
            model_name='librarypage',
            name='contact_description',
            field=models.TextField(blank=True, max_length=50, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='librarypage',
            name='contact_description_en',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='librarypage',
            name='contact_description_sl',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='librarypage',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='librarypage',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='librarypage',
            name='website',
            field=models.URLField(blank=True, verbose_name='Spletna stran'),
        ),
        migrations.AlterField(
            model_name='marketstorepage',
            name='contact_description',
            field=models.TextField(blank=True, max_length=50, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='marketstorepage',
            name='contact_description_en',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='marketstorepage',
            name='contact_description_sl',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='marketstorepage',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='marketstorepage',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='marketstorepage',
            name='website',
            field=models.URLField(blank=True, verbose_name='Spletna stran'),
        ),
        migrations.AlterField(
            model_name='residencepage',
            name='contact_description',
            field=models.TextField(blank=True, max_length=50, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='residencepage',
            name='contact_description_en',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='residencepage',
            name='contact_description_sl',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='residencepage',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='residencepage',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='residencepage',
            name='website',
            field=models.URLField(blank=True, verbose_name='Spletna stran'),
        ),
        migrations.AlterField(
            model_name='studiopage',
            name='contact_description',
            field=models.TextField(blank=True, max_length=50, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='studiopage',
            name='contact_description_en',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='studiopage',
            name='contact_description_sl',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Dodatna informacija'),
        ),
        migrations.AlterField(
            model_name='studiopage',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='studiopage',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='studiopage',
            name='website',
            field=models.URLField(blank=True, verbose_name='Spletna stran'),
        ),
    ]
