# Generated by Django 4.1.10 on 2023-08-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_labpage_archived_from_labpage_archived_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='show_see_more_section',
            field=models.BooleanField(default=False, verbose_name='Pokaži več'),
        ),
    ]
