# Generated by Django 4.1.10 on 2023-09-01 09:48

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0084_alter_contentpage_body_alter_contentpage_body_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labpage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Slika"
                                    ),
                                ),
                                (
                                    "image_description",
                                    wagtail.blocks.TextBlock(label="Podnapis k sliki"),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Galerija",
            ),
        ),
    ]
