# Generated by Django 4.1.11 on 2023-10-13 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_basictextpage_meta_image_contentpage_meta_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasettings',
            name='meta_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Meta slika'),
        ),
    ]
