# Generated by Django 4.1.11 on 2024-01-10 11:51

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0101_alter_metasettings_meta_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasettings',
            name='organization_working_hours_en',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura')), ('notice', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('text', wagtail.blocks.CharBlock(label='Opomba'))], label='Dan in opomba'))], blank=True, null=True, use_json_field=True, verbose_name='Delovni čas organizacije'),
        ),
        migrations.AddField(
            model_name='metasettings',
            name='organization_working_hours_sl',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura')), ('notice', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('text', wagtail.blocks.CharBlock(label='Opomba'))], label='Dan in opomba'))], blank=True, null=True, use_json_field=True, verbose_name='Delovni čas organizacije'),
        ),
    ]
