# Generated by Django 4.1.11 on 2024-01-16 13:10

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0102_metasettings_organization_working_hours_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metasettings",
            name="footer_links_en",
            field=wagtail.fields.StreamField(
                [
                    (
                        "page_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(
                                        help_text="Če je prazno, se uporabi naslov strani.",
                                        label="Ime",
                                        required=False,
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(label="Stran"),
                                ),
                                (
                                    "link_type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("primary_button", "Primarni gumb"),
                                            ("secondary_button", "Sekundarni gumb"),
                                            ("link", "Povezava s puščico"),
                                        ],
                                        label="Tip povezave",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "external_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock(label="Ime")),
                                ("url", wagtail.blocks.URLBlock(label="URL")),
                                (
                                    "link_type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("primary_button", "Primarni gumb"),
                                            ("secondary_button", "Sekundarni gumb"),
                                            ("link", "Povezava s puščico"),
                                        ],
                                        label="Tip povezave",
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Povezave v nogi",
            ),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="footer_links_sl",
            field=wagtail.fields.StreamField(
                [
                    (
                        "page_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(
                                        help_text="Če je prazno, se uporabi naslov strani.",
                                        label="Ime",
                                        required=False,
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(label="Stran"),
                                ),
                                (
                                    "link_type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("primary_button", "Primarni gumb"),
                                            ("secondary_button", "Sekundarni gumb"),
                                            ("link", "Povezava s puščico"),
                                        ],
                                        label="Tip povezave",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "external_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock(label="Ime")),
                                ("url", wagtail.blocks.URLBlock(label="URL")),
                                (
                                    "link_type",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("primary_button", "Primarni gumb"),
                                            ("secondary_button", "Sekundarni gumb"),
                                            ("link", "Povezava s puščico"),
                                        ],
                                        label="Tip povezave",
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Povezave v nogi",
            ),
        ),
    ]
