# Generated by Django 4.1.11 on 2024-02-07 08:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0103_metasettings_footer_links_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarypage',
            name='working_hours_en',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura'))], blank=True, null=True, use_json_field=True, verbose_name='Delovni čas'),
        ),
        migrations.AddField(
            model_name='librarypage',
            name='working_hours_sl',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura'))], blank=True, null=True, use_json_field=True, verbose_name='Delovni čas'),
        ),
        migrations.AddField(
            model_name='marketstorepage',
            name='working_hours_en',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura'))], blank=True, null=True, use_json_field=True, verbose_name='Delovni čas'),
        ),
        migrations.AddField(
            model_name='marketstorepage',
            name='working_hours_sl',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura'))], blank=True, null=True, use_json_field=True, verbose_name='Delovni čas'),
        ),
        migrations.AddField(
            model_name='residencepage',
            name='working_hours_en',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura'))], blank=True, null=True, use_json_field=True, verbose_name='Delovni čas'),
        ),
        migrations.AddField(
            model_name='residencepage',
            name='working_hours_sl',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura'))], blank=True, null=True, use_json_field=True, verbose_name='Delovni čas'),
        ),
        migrations.AddField(
            model_name='studiopage',
            name='working_hours_en',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura'))], blank=True, null=True, use_json_field=True, verbose_name='Delovni čas'),
        ),
        migrations.AddField(
            model_name='studiopage',
            name='working_hours_sl',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura'))], blank=True, null=True, use_json_field=True, verbose_name='Delovni čas'),
        ),
    ]
