# Generated by Django 4.1.11 on 2024-02-07 09:29

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0104_librarypage_working_hours_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metasettings",
            name="footer_logos_en",
            field=wagtail.fields.StreamField(
                [
                    (
                        "logo",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "description",
                                    wagtail.blocks.CharBlock(
                                        blank=True, label="Naslov", required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Logotipi",
            ),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="footer_logos_sl",
            field=wagtail.fields.StreamField(
                [
                    (
                        "logo",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "description",
                                    wagtail.blocks.CharBlock(
                                        blank=True, label="Naslov", required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Logotipi",
            ),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="header_marquee_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Vrteče besedilo"
            ),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="header_marquee_sl",
            field=models.TextField(
                blank=True, null=True, verbose_name="Vrteče besedilo"
            ),
        ),
    ]
