# Generated by Django 4.1.11 on 2024-04-16 06:29

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0108_workingstationpage_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labpage",
            name="working_hours",
            field=wagtail.fields.StreamField(
                [
                    (
                        "time",
                        wagtail.blocks.StructBlock(
                            [
                                ("day", wagtail.blocks.CharBlock(label="Dan")),
                                (
                                    "start_time",
                                    wagtail.blocks.TimeBlock(label="Začetna ura"),
                                ),
                                (
                                    "end_time",
                                    wagtail.blocks.TimeBlock(label="Končna ura"),
                                ),
                            ],
                            label="Dan in ura",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Delovni čas",
            ),
        ),
        migrations.AlterField(
            model_name="workingstationpage",
            name="modules",
            field=wagtail.fields.StreamField(
                [
                    (
                        "bulletpoints",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.TextBlock(
                                        label="Naslov", required=False
                                    ),
                                ),
                                (
                                    "points",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.TextBlock(), label="Točka", min=1
                                    ),
                                ),
                            ],
                            label="Modul s točkami",
                        ),
                    ),
                    (
                        "description",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.TextBlock(
                                        label="Naslov", required=False
                                    ),
                                ),
                                ("description", wagtail.blocks.TextBlock(label="Opis")),
                            ],
                            label="Modul z opisom",
                        ),
                    ),
                    (
                        "specifications",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.TextBlock(
                                        label="Naslov", required=False
                                    ),
                                ),
                                (
                                    "points",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "name",
                                                    wagtail.blocks.TextBlock(
                                                        label="Specifikacija"
                                                    ),
                                                ),
                                                (
                                                    "value",
                                                    wagtail.blocks.TextBlock(
                                                        label="Vrednost"
                                                    ),
                                                ),
                                            ]
                                        ),
                                        label="Specifikacije",
                                        min=1,
                                    ),
                                ),
                            ],
                            label="Modul s specifikacijami",
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Moduli",
            ),
        ),
        migrations.AlterField(
            model_name="workingstationpage",
            name="modules_en",
            field=wagtail.fields.StreamField(
                [
                    (
                        "bulletpoints",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.TextBlock(
                                        label="Naslov", required=False
                                    ),
                                ),
                                (
                                    "points",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.TextBlock(), label="Točka", min=1
                                    ),
                                ),
                            ],
                            label="Modul s točkami",
                        ),
                    ),
                    (
                        "description",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.TextBlock(
                                        label="Naslov", required=False
                                    ),
                                ),
                                ("description", wagtail.blocks.TextBlock(label="Opis")),
                            ],
                            label="Modul z opisom",
                        ),
                    ),
                    (
                        "specifications",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.TextBlock(
                                        label="Naslov", required=False
                                    ),
                                ),
                                (
                                    "points",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "name",
                                                    wagtail.blocks.TextBlock(
                                                        label="Specifikacija"
                                                    ),
                                                ),
                                                (
                                                    "value",
                                                    wagtail.blocks.TextBlock(
                                                        label="Vrednost"
                                                    ),
                                                ),
                                            ]
                                        ),
                                        label="Specifikacije",
                                        min=1,
                                    ),
                                ),
                            ],
                            label="Modul s specifikacijami",
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Moduli",
            ),
        ),
        migrations.AlterField(
            model_name="workingstationpage",
            name="modules_sl",
            field=wagtail.fields.StreamField(
                [
                    (
                        "bulletpoints",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.TextBlock(
                                        label="Naslov", required=False
                                    ),
                                ),
                                (
                                    "points",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.TextBlock(), label="Točka", min=1
                                    ),
                                ),
                            ],
                            label="Modul s točkami",
                        ),
                    ),
                    (
                        "description",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.TextBlock(
                                        label="Naslov", required=False
                                    ),
                                ),
                                ("description", wagtail.blocks.TextBlock(label="Opis")),
                            ],
                            label="Modul z opisom",
                        ),
                    ),
                    (
                        "specifications",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.TextBlock(
                                        label="Naslov", required=False
                                    ),
                                ),
                                (
                                    "points",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "name",
                                                    wagtail.blocks.TextBlock(
                                                        label="Specifikacija"
                                                    ),
                                                ),
                                                (
                                                    "value",
                                                    wagtail.blocks.TextBlock(
                                                        label="Vrednost"
                                                    ),
                                                ),
                                            ]
                                        ),
                                        label="Specifikacije",
                                        min=1,
                                    ),
                                ),
                            ],
                            label="Modul s specifikacijami",
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Moduli",
            ),
        ),
        migrations.AlterField(
            model_name="workingstationpage",
            name="tag",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Oznaka na kartici"
            ),
        ),
        migrations.AlterField(
            model_name="workingstationpage",
            name="tag_en",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Oznaka na kartici"
            ),
        ),
        migrations.AlterField(
            model_name="workingstationpage",
            name="tag_sl",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Oznaka na kartici"
            ),
        ),
    ]
