# Generated by Django 4.1.11 on 2024-04-16 06:32

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0109_labpage_working_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labpage",
            name="notice",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Dodatno obvestilo"
            ),
        ),
        migrations.AddField(
            model_name="labpage",
            name="notice_en",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Dodatno obvestilo"
            ),
        ),
        migrations.AddField(
            model_name="labpage",
            name="notice_sl",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Dodatno obvestilo"
            ),
        ),
        migrations.AddField(
            model_name="labpage",
            name="working_hours_en",
            field=wagtail.fields.StreamField(
                [
                    (
                        "time",
                        wagtail.blocks.StructBlock(
                            [
                                ("day", wagtail.blocks.CharBlock(label="Dan")),
                                (
                                    "start_time",
                                    wagtail.blocks.TimeBlock(label="Začetna ura"),
                                ),
                                (
                                    "end_time",
                                    wagtail.blocks.TimeBlock(label="Končna ura"),
                                ),
                            ],
                            label="Dan in ura",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Delovni čas",
            ),
        ),
        migrations.AddField(
            model_name="labpage",
            name="working_hours_sl",
            field=wagtail.fields.StreamField(
                [
                    (
                        "time",
                        wagtail.blocks.StructBlock(
                            [
                                ("day", wagtail.blocks.CharBlock(label="Dan")),
                                (
                                    "start_time",
                                    wagtail.blocks.TimeBlock(label="Začetna ura"),
                                ),
                                (
                                    "end_time",
                                    wagtail.blocks.TimeBlock(label="Končna ura"),
                                ),
                            ],
                            label="Dan in ura",
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Delovni čas",
            ),
        ),
    ]
