# Generated by Django 4.1.11 on 2024-04-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0110_labpage_notice_labpage_notice_en_labpage_notice_sl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workingstationpage",
            name="show_see_more_section",
            field=models.BooleanField(default=True, verbose_name="Pokaži več"),
        ),
    ]
