# Generated by Django 4.1.11 on 2024-06-20 07:40

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0114_alter_contentpage_body_alter_contentpage_body_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lablistpage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='lablistpage',
            name='intro_text_en',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='lablistpage',
            name='intro_text_sl',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='marketstorelistpage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='marketstorelistpage',
            name='intro_text_en',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='marketstorelistpage',
            name='intro_text_sl',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='residencelistpage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='residencelistpage',
            name='intro_text_en',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='residencelistpage',
            name='intro_text_sl',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='studiolistpage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='studiolistpage',
            name='intro_text_en',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='studiolistpage',
            name='intro_text_sl',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Opis'),
        ),
    ]
