# Generated by Django 4.1.11 on 2024-07-01 19:02

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0115_alter_lablistpage_intro_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasettings',
            name='labs_working_hours',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura')), ('notice', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('text', wagtail.blocks.CharBlock(label='Opomba'))], label='Dan in opomba'))], blank=True, null=True, use_json_field=True, verbose_name='Delovni čas laboratorijev'),
        ),
        migrations.AddField(
            model_name='metasettings',
            name='labs_working_hours_en',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura')), ('notice', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('text', wagtail.blocks.CharBlock(label='Opomba'))], label='Dan in opomba'))], blank=True, null=True, use_json_field=True, verbose_name='Delovni čas laboratorijev'),
        ),
        migrations.AddField(
            model_name='metasettings',
            name='labs_working_hours_sl',
            field=wagtail.fields.StreamField([('time', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('start_time', wagtail.blocks.TimeBlock(label='Začetna ura')), ('end_time', wagtail.blocks.TimeBlock(label='Končna ura'))], label='Dan in ura')), ('notice', wagtail.blocks.StructBlock([('day', wagtail.blocks.CharBlock(label='Dan')), ('text', wagtail.blocks.CharBlock(label='Opomba'))], label='Dan in opomba'))], blank=True, null=True, use_json_field=True, verbose_name='Delovni čas laboratorijev'),
        ),
        migrations.AddField(
            model_name='metasettings',
            name='organization_notice',
            field=models.TextField(blank=True, null=True, verbose_name='Delovni čas info'),
        ),
        migrations.AddField(
            model_name='metasettings',
            name='organization_notice_en',
            field=models.TextField(blank=True, null=True, verbose_name='Delovni čas info'),
        ),
        migrations.AddField(
            model_name='metasettings',
            name='organization_notice_sl',
            field=models.TextField(blank=True, null=True, verbose_name='Delovni čas info'),
        ),
    ]
