# Generated by Django 4.1.11 on 2024-07-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0119_metasettings_labs_working_hours_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metasettings",
            name="labs_working_hours_title_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Delovni čas laboratorijev - naslov"
            ),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="labs_working_hours_title_sl",
            field=models.TextField(
                blank=True, null=True, verbose_name="Delovni čas laboratorijev - naslov"
            ),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="organization_working_hours_title_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Delovni čas organizacije - naslov"
            ),
        ),
        migrations.AddField(
            model_name="metasettings",
            name="organization_working_hours_title_sl",
            field=models.TextField(
                blank=True, null=True, verbose_name="Delovni čas organizacije - naslov"
            ),
        ),
    ]
