# Generated by Django 4.1.11 on 2024-08-01 17:07

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0122_labpage_lab_lead_phone_alter_labpage_working_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labpage',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='labpage',
            name='button_text_en',
        ),
        migrations.RemoveField(
            model_name='labpage',
            name='button_text_sl',
        ),
        migrations.AddField(
            model_name='labpage',
            name='button_en',
            field=wagtail.fields.StreamField([('external', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.TextBlock(label='Besedilo na gumbu')), ('link', wagtail.blocks.URLBlock(label='Povezava'))], label='Zunanji URL')), ('page', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.TextBlock(label='Besedilo na gumbu')), ('page', wagtail.blocks.PageChooserBlock(label='Podstran'))], label='Podstran'))], blank=True, null=True, use_json_field=True, verbose_name='Gumb'),
        ),
        migrations.AddField(
            model_name='labpage',
            name='button_sl',
            field=wagtail.fields.StreamField([('external', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.TextBlock(label='Besedilo na gumbu')), ('link', wagtail.blocks.URLBlock(label='Povezava'))], label='Zunanji URL')), ('page', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.TextBlock(label='Besedilo na gumbu')), ('page', wagtail.blocks.PageChooserBlock(label='Podstran'))], label='Podstran'))], blank=True, null=True, use_json_field=True, verbose_name='Gumb'),
        ),
        migrations.AlterField(
            model_name='labpage',
            name='button',
            field=wagtail.fields.StreamField([('external', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.TextBlock(label='Besedilo na gumbu')), ('link', wagtail.blocks.URLBlock(label='Povezava'))], label='Zunanji URL')), ('page', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.TextBlock(label='Besedilo na gumbu')), ('page', wagtail.blocks.PageChooserBlock(label='Podstran'))], label='Podstran'))], blank=True, null=True, use_json_field=True, verbose_name='Gumb'),
        ),
    ]
