# Generated by Django 4.2.15 on 2025-02-13 15:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0123_remove_labpage_button_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['sort_order'], 'verbose_name': 'Orodje', 'verbose_name_plural': 'Orodja'},
        ),
        migrations.AlterModelOptions(
            name='toolspecification',
            options={'ordering': ['sort_order'], 'verbose_name': 'Specifikacija orodja', 'verbose_name_plural': 'Specifikacije orodja'},
        ),
        migrations.AlterField(
            model_name='customrendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width'),
        ),
        migrations.AlterField(
            model_name='workingstationpage',
            name='modules',
            field=wagtail.fields.StreamField([('bulletpoints', 3), ('description', 5), ('specifications', 10)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Naslov', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.ListBlock', (1,), {'label': 'Točka', 'min': 1}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('points', 2)]], {'label': 'Modul s točkami'}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Opis'}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 4)]], {'label': 'Modul z opisom'}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Specifikacija'}), 7: ('wagtail.blocks.TextBlock', (), {'label': 'Vrednost'}), 8: ('wagtail.blocks.StructBlock', [[('name', 6), ('value', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Specifikacije', 'min': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('points', 9)]], {'label': 'Modul s specifikacijami'})}, null=True, verbose_name='Moduli'),
        ),
        migrations.AlterField(
            model_name='workingstationpage',
            name='modules_en',
            field=wagtail.fields.StreamField([('bulletpoints', 3), ('description', 5), ('specifications', 10)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Naslov', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.ListBlock', (1,), {'label': 'Točka', 'min': 1}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('points', 2)]], {'label': 'Modul s točkami'}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Opis'}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 4)]], {'label': 'Modul z opisom'}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Specifikacija'}), 7: ('wagtail.blocks.TextBlock', (), {'label': 'Vrednost'}), 8: ('wagtail.blocks.StructBlock', [[('name', 6), ('value', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Specifikacije', 'min': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('points', 9)]], {'label': 'Modul s specifikacijami'})}, null=True, verbose_name='Moduli'),
        ),
        migrations.AlterField(
            model_name='workingstationpage',
            name='modules_sl',
            field=wagtail.fields.StreamField([('bulletpoints', 3), ('description', 5), ('specifications', 10)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Naslov', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.ListBlock', (1,), {'label': 'Točka', 'min': 1}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('points', 2)]], {'label': 'Modul s točkami'}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Opis'}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 4)]], {'label': 'Modul z opisom'}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Specifikacija'}), 7: ('wagtail.blocks.TextBlock', (), {'label': 'Vrednost'}), 8: ('wagtail.blocks.StructBlock', [[('name', 6), ('value', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Specifikacije', 'min': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('points', 9)]], {'label': 'Modul s specifikacijami'})}, null=True, verbose_name='Moduli'),
        ),
        migrations.AlterField(
            model_name='workingstationpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Predogledna slika (če je prazno, se bo uporabila zgornja slika)'),
        ),
    ]
