# Generated by Django 4.2.15 on 2025-05-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0125_metasettings_holidays_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='name_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='name_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='toolspecification',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Specifikacija'),
        ),
        migrations.AddField(
            model_name='toolspecification',
            name='name_sl',
            field=models.TextField(null=True, verbose_name='Specifikacija'),
        ),
        migrations.AddField(
            model_name='toolspecification',
            name='value_en',
            field=models.TextField(null=True, verbose_name='Vrednost'),
        ),
        migrations.AddField(
            model_name='toolspecification',
            name='value_sl',
            field=models.TextField(null=True, verbose_name='Vrednost'),
        ),
    ]
