# Generated by Django 5.2.1 on 2026-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0128_alter_contentpage_body_alter_contentpage_body_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='prima_id',
            field=models.CharField(default=1, max_length=255, verbose_name='Prima ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='prima_group_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Prima group id'),
        ),
        migrations.AlterField(
            model_name='workingstationpage',
            name='prima_group_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Prima group id'),
        ),
    ]
