# Generated by Django 5.2.1 on 2026-05-05 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0129_workshop_prima_id_alter_tool_prima_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='home.labpage', verbose_name='Laboratorij'),
        ),
    ]
