# Generated by Django 4.1.9 on 2023-06-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_membership_user_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="address_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
