# Generated by Django 4.1.9 on 2023-06-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_address_1_user_address_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="public_profile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="public_username",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="address_1",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="address_2",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
            preserve_default=False,
        ),
    ]
