# Generated by Django 4.1.9 on 2023-06-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_payment_plan_token_payment_plan_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
