# Generated by Django 4.1.9 on 2023-06-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_membershiptype_remove_membership_end_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.membershiptype'),
            preserve_default=False,
        ),
    ]
