# Generated by Django 4.1.9 on 2023-06-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
