# Generated by Django 4.1.9 on 2023-07-01 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_membershiptype_price_membershiptype_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Ime kategorije")),
            ],
            options={
                "verbose_name": "Kategorija zanimanj",
                "verbose_name_plural": "Kategorije zanimanj",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="link",
        ),
        migrations.AddField(
            model_name="user",
            name="contact",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Kontakt"),
        ),
        migrations.AddField(
            model_name="user",
            name="link_1",
            field=models.URLField(
                blank=True, verbose_name="Povezava do spletne strani"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="link_2",
            field=models.URLField(
                blank=True, verbose_name="Povezava do spletne strani"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="link_3",
            field=models.URLField(
                blank=True, verbose_name="Povezava do spletne strani"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address_1",
            field=models.CharField(blank=True, max_length=200, verbose_name="Naslov 1"),
        ),
        migrations.AlterField(
            model_name="user",
            name="address_2",
            field=models.CharField(blank=True, max_length=200, verbose_name="Naslov 2"),
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, verbose_name="Opis"),
        ),
        migrations.AlterField(
            model_name="user",
            name="legal_person_address_1",
            field=models.CharField(blank=True, max_length=200, verbose_name="Naslov 1"),
        ),
        migrations.AlterField(
            model_name="user",
            name="legal_person_address_2",
            field=models.CharField(blank=True, max_length=200, verbose_name="Naslov 2"),
        ),
        migrations.AlterField(
            model_name="user",
            name="legal_person_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Naziv pravne osebe"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="legal_person_tax_number",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Davčna številka"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="legal_person_vat",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Zavezanec za DDV"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.membership",
                verbose_name="Članarina",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_profile",
            field=models.BooleanField(
                default=False, verbose_name="Profil naj bo javno viden"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_username",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Uporabniško ime"
            ),
        ),
    ]
