# Generated by Django 4.1.9 on 2023-07-01 09:11

import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("image", wagtail.images.blocks.ImageChooserBlock())],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Galerija",
            ),
        ),
    ]
