# Generated by Django 4.1.10 on 2023-08-23 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_user_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="notification_14_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membership",
            name="notification_1_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membership",
            name="notification_30_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membership",
            name="notification_7_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.membership",
                verbose_name="Članarina",
            ),
        ),
    ]
