# Generated by Django 4.1.10 on 2023-08-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_auto_20230823_1632"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="membership",
        ),
    ]
