# Generated by Django 4.1.11 on 2023-09-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_user_legal_person_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="Datum rojstva"),
        ),
    ]
