# Generated by Django 4.1.11 on 2023-09-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='notification_14_sent',
        ),
    ]
