# Generated by Django 4.1.11 on 2023-10-09 05:43

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_membership_notification_14_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gallery',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, default=[], use_json_field=True, verbose_name='Galerija'),
        ),
    ]
