# Generated by Django 4.1.11 on 2023-10-10 10:37

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_membership_created_at_membership_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gallery',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, default=[], use_json_field=True, verbose_name='Galerija'),
        ),
    ]
