# Generated by Django 4.1.11 on 2023-10-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_user_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'ženski'), ('M', 'moški'), ('O', 'drugo')], max_length=1, verbose_name='Spol'),
        ),
    ]
