# Generated by Django 4.1.11 on 2024-01-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_in_pantheon',
            field=models.BooleanField(default=False, help_text='Ali je oseba že shranjena v Pantheonu?'),
        ),
    ]
