# Generated by Django 4.1.11 on 2024-03-20 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0048_plan_extend_membership"),
        ("users", "0035_user_saved_in_pantheon"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="extended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.plan",
            ),
        ),
    ]
