# Generated by Django 4.2.15 on 2025-03-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_marketing',
            field=models.BooleanField(default=False, verbose_name='Allow e-mail marketning?'),
        ),
    ]
