# Generated by Django 5.2.1 on 2025-09-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_user_allow_marketing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinterest',
            old_name='name',
            new_name='name_old',
        ),
    ]
