# Generated by Django 5.2.1 on 2025-09-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_rename_name_userinterest_name_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='name',
            field=models.TextField(default='', verbose_name='Ime kategorije'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinterest',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Ime kategorije'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='name_sl',
            field=models.TextField(null=True, verbose_name='Ime kategorije'),
        ),
    ]
