# Generated by Django 5.2.1 on 2025-09-12 09:51

from django.db import migrations
from django.db.models import F


def set_user_interest_slo_word(apps, schema_editor):
    UserInterest = apps.get_model("users", "UserInterest")
    UserInterest.objects.all().update(name_sl=F("name_old"))

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_userinterest_name_userinterest_name_en_and_more'),
    ]

    operations = [migrations.RunPython(set_user_interest_slo_word)
    ]
