# Generated by Django 5.2.1 on 2025-09-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20250912_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiptypespecification',
            old_name='name',
            new_name='name_old',
        ),
    ]
