# Generated by Django 5.2.1 on 2025-09-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_rename_name_membershiptypespecification_name_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptypespecification',
            name='name',
            field=models.TextField(default='', verbose_name='Boniteta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershiptypespecification',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Boniteta'),
        ),
        migrations.AddField(
            model_name='membershiptypespecification',
            name='name_sl',
            field=models.TextField(null=True, verbose_name='Boniteta'),
        ),
    ]
