# Generated by Django 5.2.1 on 2025-09-12 11:04

from django.db import migrations
from django.db.models import F

def set_membership_type_specification_slo_word(apps, schema_editor):
    MembershipTypeSpecification = apps.get_model("users", "MembershipTypeSpecification")
    MembershipTypeSpecification.objects.all().update(name_sl=F("name_old"))

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_membershiptypespecification_name_and_more'),
    ]

    operations = [migrations.RunPython(set_membership_type_specification_slo_word)]
