# Generated by Django 5.2.1 on 2025-09-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20250912_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptypespecification',
            name='name_old',
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='name_old',
        ),
    ]
