# Generated by Django 5.2.1 on 2025-09-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_remove_membershiptypespecification_name_old_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiptype',
            old_name='name',
            new_name='name_old',
        ),
    ]
