# Generated by Django 5.2.1 on 2025-09-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_rename_name_membershiptype_name_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='name',
            field=models.TextField(default='', verbose_name='Ime članstva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Ime članstva'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='name_sl',
            field=models.TextField(null=True, verbose_name='Ime članstva'),
        ),
    ]
