# Generated by Django 5.2.1 on 2025-09-12 11:25

from django.db import migrations
from django.db.models import F

def set_membership_type_slo_word(apps, schema_editor):
    MembershipType = apps.get_model("users", "MembershipType")
    MembershipType.objects.all().update(name_sl=F("name_old"))

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_membershiptype_name_membershiptype_name_en_and_more'),
    ]

    operations = [migrations.RunPython(set_membership_type_slo_word)]