# Generated by Django 5.2.1 on 2025-09-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20250912_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptype',
            name='name_old',
        ),
    ]
