# Generated by Django 5.2.1 on 2025-09-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_remove_membershiptype_name_old'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiptypespecification',
            options={'ordering': ['sort_order'], 'verbose_name': 'Boniteta članstva', 'verbose_name_plural': 'Bonitete članstva'},
        ),
    ]
