# Generated by Django 5.2.1 on 2025-12-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_alter_membershiptypespecification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prima_group_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Group ID which is assigned in Prima'),
        ),
    ]
