# Generated by Django 5.2.1 on 2026-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_user_prima_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prima_group_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Group ID which is assigned in Prima'),
        ),
    ]
