# Generated by Django 5.2.1 on 2026-07-21 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_alter_user_prima_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv organizacije')),
                ('address_1', models.CharField(blank=True, max_length=200, verbose_name='Naslov 1')),
                ('address_2', models.CharField(blank=True, max_length=200, verbose_name='Naslov 2')),
                ('tax_number', models.CharField(blank=True, max_length=200, verbose_name='Davčna številka')),
                ('vat', models.BooleanField(default=False, verbose_name='Zavezanec za DDV')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Vodja organizacije')),
            ],
            options={
                'verbose_name': 'Organizacija',
                'verbose_name_plural': 'Organizacije',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.organization', verbose_name='Organizacija'),
        ),
    ]
