# Generated by Django 5.2.1 on 2026-08-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_organization_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='package_valid_to',
            field=models.DateField(blank=True, help_text='When the plan expires', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='prima_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prima ID'),
        ),
    ]
