# Generated by Django 4.1.9 on 2023-06-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="valid_from",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the plan starts", null=True
            ),
        ),
    ]
