# Generated by Django 4.1.9 on 2023-06-24 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_alter_plan_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='active_to',
            field=models.DateTimeField(blank=True, help_text='When subscription expires', null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='type_of',
            field=models.CharField(choices=[('LAB', 'Lab'), ('WORKSHOP', 'Workshop')], default='LAB', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(help_text='Select a user', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tokens',
            field=models.IntegerField(default=0, help_text='How many tokens a user gets'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='workshops',
            field=models.IntegerField(blank=True, default=0, help_text='How many workshops the user receives', null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='payments.payment'),
        ),
    ]
