# Generated by Django 4.1.9 on 2023-06-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_plan_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={
                "verbose_name": "Plačilni paket",
                "verbose_name_plural": "Plačilni paket",
            },
        ),
    ]
