# Generated by Django 4.1.10 on 2023-08-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_plan_pantheon_ident_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='vat',
            field=models.IntegerField(default=22),
        ),
    ]
