# Generated by Django 4.1.10 on 2023-08-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_plan_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='saved_in_pantheon',
            field=models.BooleanField(default=False),
        ),
    ]
