# Generated by Django 4.1.10 on 2023-08-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20230831_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
    ]
