# Generated by Django 4.1.10 on 2023-08-31 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_itemtype_plan_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='payments.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
