# Generated by Django 4.1.11 on 2023-09-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_paymentplan_payment_alter_paymentplan_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=100)),
                ('valid_to', models.DateTimeField(help_text='When does the code expire?')),
                ('percent_discount', models.IntegerField()),
                ('single_use', models.BooleanField()),
                ('number_of_uses', models.IntegerField(default=0)),
                ('code_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.itemtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
