# Generated by Django 4.1.11 on 2023-09-05 15:09

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0018_promocode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="code",
            field=models.CharField(
                default=payments.models.generate_promo_code, max_length=100
            ),
        ),
    ]
