# Generated by Django 4.1.11 on 2023-09-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_alter_promocode_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Naročilo', 'verbose_name_plural': 'Naročila'},
        ),
        migrations.RenameField(
            model_name='promocode',
            old_name='code_type',
            new_name='item_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text='The promo code used for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.promocode'),
        ),
    ]
