# Generated by Django 4.1.11 on 2023-09-19 10:07

from django.db import migrations

def copy_names(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")

    payments = Payment.objects.all()
    for payment in payments:
        for payment_plan in payment.payment_plans.all():
            payment_plan.plan_name = payment_plan.plan.name
            payment_plan.save()

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_paymentplan_plan_name'),
    ]

    operations = [
        migrations.RunPython(copy_names)
    ]
