# Generated by Django 4.1.11 on 2023-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0026_auto_20230919_1207"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplan",
            name="valid_to",
            field=models.DateTimeField(
                blank=True, help_text="When subscription expires", null=True
            ),
        ),
    ]
