# Generated by Django 4.1.11 on 2023-09-20 12:31

from django.db import migrations

def migrate_uporabnina_valid_to(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")

    payments = Payment.objects.all()
    for payment in payments:
        payment.payment_plans.all().update(valid_to=payment.active_to)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_paymentplan_valid_to'),
    ]

    operations = [
        migrations.RunPython(migrate_uporabnina_valid_to)
    ]
