# Generated by Django 4.1.11 on 2023-09-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0029_paymentplan_notification_1_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
