# Generated by Django 4.1.11 on 2023-10-19 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_alter_user_gallery"),
        ("payments", "0032_alter_payment_payment_done_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.membership",
            ),
        ),
    ]
