# Generated by Django 4.1.11 on 2023-12-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0029_eventpage_contact_email_eventpage_labs_and_more"),
        ("payments", "0033_payment_membership"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PaymentPlan",
            new_name="PaymentPlanEvent",
        ),
        migrations.AddField(
            model_name="paymentplanevent",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_plans",
                to="events.eventpage",
            ),
        ),
        migrations.AddField(
            model_name="paymentplanevent",
            name="kind",
            field=models.CharField(
                choices=[("PLAN", "Plan"), ("EVENT", "Event")],
                default="PLAN",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paymentplanevent",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.plan",
                related_name="payment_plans",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="items",
            field=models.ManyToManyField(
                help_text="Items in payment",
                related_name="payments",
                through="payments.PaymentPlanEvent",
                to="payments.plan",
            ),
        ),
    ]
