# Generated by Django 4.1.11 on 2023-12-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0033_payment_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
