# Generated by Django 4.1.11 on 2023-11-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_eventpage_contact_email_eventpage_labs_and_more'),
        ('payments', '0033_payment_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PLAN', 'Plan'), ('EVENT', 'Event')], default='PLAN', max_length=20)),
                ('plan_name', models.CharField(help_text='Npr. letna uporabnina', max_length=100, verbose_name='Ime paketa na dan nakupa')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_to', models.DateTimeField(blank=True, help_text='When subscription expires', null=True)),
                ('notification_30_sent', models.BooleanField(default=False)),
                ('notification_7_sent', models.BooleanField(default=False)),
                ('notification_1_sent', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='events.eventpage')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='payments.payment')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='payments.plan')),
                ('promo_code', models.ForeignKey(blank=True, help_text='The promo code used for this payment plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans', to='payments.promocode')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
        migrations.AlterField(
            model_name='payment',
            name='items',
            field=models.ManyToManyField(help_text='Items in payment', related_name='payments', through='payments.PaymentPlanEvent', to='payments.plan'),
        ),
    ]
