# Generated by Django 4.1.11 on 2023-12-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0035_auto_20231205_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
