# Generated by Django 4.1.11 on 2023-12-06 09:42

from django.db import migrations

def migrate_original_amount(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")

    payments = Payment.objects.all()
    for payment in payments:
        payment.original_amount = 0
        for item in payment.items.all():
            payment.original_amount += item.price
        payment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0036_payment_original_amount'),
    ]

    operations = [
        migrations.RunPython(migrate_original_amount)
    ]
