# Generated by Django 4.1.11 on 2023-12-06 18:02

from django.db import migrations

def migrate_payment_item_type(apps, schema_editor):
    PaymentPlanEvent = apps.get_model("payments", "PaymentPlanEvent")

    payment_plan_events = PaymentPlanEvent.objects.all()
    for payment_plan_event in payment_plan_events:
        if payment_plan_event.plan:
            payment_plan_event.payment_item_type = payment_plan_event.plan.payment_item_type
            payment_plan_event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0037_remove_paymentplanevent_kind_remove_plan_item_type_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_payment_item_type)
    ]
