# Generated by Django 4.1.11 on 2023-12-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0038_auto_20231206_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemType',
        ),
    ]
