# Generated by Django 4.1.11 on 2023-12-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0039_delete_itemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original amount before discount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentplanevent',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentplanevent',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='payments.plan'),
        ),
    ]
