# Generated by Django 4.1.11 on 2023-12-07 16:58

from django.db import migrations

def migrate_original_amount(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")

    payments = Payment.objects.all()
    for payment in payments:
        payment.original_amount = 0
        for item in payment.items.all():
            payment.original_amount += item.price
        payment.save()


def migrate_original_price(apps, schema_editor):
    PaymentPlanEvent = apps.get_model("payments", "PaymentPlanEvent")

    payment_plans = PaymentPlanEvent.objects.all()
    for payment_plan in payment_plans:
        if payment_plan.plan:
            payment_plan.original_price = payment_plan.plan.price
            payment_plan.save()
        else:
            payment_plan.original_price = payment_plan.event_registration.event.price
            payment_plan.save()

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0040_payment_original_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_original_amount),
        migrations.RunPython(migrate_original_price)
    ]
