# Generated by Django 4.1.11 on 2024-01-16 12:02

from django.db import migrations


def migrate_payment_ujp_fix(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")

    payments = Payment.objects.all()
    for payment in payments:
        payment.ujp_id = payment.id

        payment.transaction_success_at = payment.payment_done_at

        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0043_payment_ujp_id"),
    ]

    operations = [migrations.RunPython(migrate_payment_ujp_fix)]
