# Generated by Django 4.1.11 on 2024-02-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_remove_eventpage_pantheon_ident_and_more'),
        ('payments', '0046_plan_saved_in_pantheon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplanevent',
            name='event_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans', to='events.eventregistration'),
        ),
        migrations.AlterField(
            model_name='paymentplanevent',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='paymentplanevent',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans', to='payments.plan'),
        ),
    ]
