# Generated by Django 4.1.11 on 2024-03-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0047_alter_paymentplanevent_event_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='extend_membership',
            field=models.BooleanField(default=False, help_text='Should this plan extend the membership if needed?'),
        ),
    ]
