# Generated by Django 4.1.11 on 2024-03-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0049_plan_description_en_plan_description_item_1_en_and_more'),
        ('payments', '0051_auto_20240320_2121'),
    ]

    operations = [
    ]
