# Generated by Django 4.1.11 on 2024-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0052_merge_20240321_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='number_of_uses',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
