# Generated by Django 4.2.15 on 2024-08-13 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0040_alter_eventpage_labs"),
        ("payments", "0054_promocode_last_entry_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="event_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Select event to limit promo code to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promo_codes",
                to="events.eventpage",
                verbose_name="Dogodek",
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Select plan to limit promo code to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promo_codes",
                to="payments.plan",
                verbose_name="Plan",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="payment_item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("clanarina", "Clanarina"),
                    ("uporabnina", "Uporabnina"),
                    ("event", "Dogodek"),
                    ("training", "Usposabljanje"),
                ],
                default="clanarina",
                max_length=20,
                null=True,
                verbose_name="Tip storitve",
            ),
        ),
    ]
