# Generated by Django 4.2.15 on 2025-03-13 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0055_promocode_event_page_promocode_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Select user to limit promo code to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to user'),
        ),
    ]
