# Generated by Django 4.2.15 on 2025-05-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0056_promocode_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='redirect_after_success',
            field=models.CharField(blank=True, help_text='Where to redirect after success', max_length=256, null=True),
        ),
    ]
