# Generated by Django 5.2.1 on 2025-05-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0057_payment_redirect_after_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplanevent',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='When subscription starts', null=True),
        ),
    ]
