# Generated by Django 5.2.1 on 2025-05-20 05:57

from django.db import migrations

def set_valid_to_payment_plans(apps, schema_editor):
    PaymentPlanEvent = apps.get_model("payments", "PaymentPlanEvent")

    payment_plans = PaymentPlanEvent.objects.filter(
        valid_from=None,
        payment__successed_at__isnull=False,
    )
    for payment_plan in payment_plans:
        payment_plan.valid_from = payment_plan.payment.successed_at
        payment_plan.save()

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0058_paymentplanevent_valid_from'),
    ]

    operations = [
        migrations.RunPython(set_valid_to_payment_plans)
    ]
