# Generated by Django 5.2.1 on 2025-07-09 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0059_auto_20250520_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='percent_discount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
