# Generated by Django 5.2.1 on 2025-12-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0060_alter_promocode_percent_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='prima_group_id',
            field=models.IntegerField(blank=True, help_text='Prima subscription group id associated with this plan', null=True),
        ),
    ]
