# Generated by Django 5.2.1 on 2025-12-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0061_plan_prima_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_price', models.DecimalField(decimal_places=2, default=8.0, max_digits=10, verbose_name='Cena žetona')),
                ('special_price', models.DecimalField(decimal_places=2, default=8.0, max_digits=10, verbose_name='Posebna cena žetona (študente in upokojence)')),
                ('max_purchase_quantity', models.IntegerField(default=10, verbose_name='Maksimalno število žetonov na nakup')),
            ],
            options={
                'verbose_name': 'Nastavitve žetonov',
                'verbose_name_plural': 'Nastavitve žetonov',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='tokens_added_to_wallet_at',
            field=models.DateTimeField(blank=True, help_text="When tokens have been successfully added to user's wallet after payment", null=True),
        ),
        migrations.AddField(
            model_name='paymentplanevent',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paymentplanevent',
            name='payment_item_type',
            field=models.CharField(choices=[('clanarina', 'Clanarina'), ('uporabnina', 'Uporabnina'), ('event', 'Dogodek'), ('training', 'Usposabljanje'), ('tokens', 'Žetoni')], default='clanarina', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='payment_item_type',
            field=models.CharField(choices=[('clanarina', 'Clanarina'), ('uporabnina', 'Uporabnina'), ('event', 'Dogodek'), ('training', 'Usposabljanje'), ('tokens', 'Žetoni')], default='clanarina', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='payment_item_type',
            field=models.CharField(blank=True, choices=[('clanarina', 'Clanarina'), ('uporabnina', 'Uporabnina'), ('event', 'Dogodek'), ('training', 'Usposabljanje'), ('tokens', 'Žetoni')], default='clanarina', max_length=20, null=True, verbose_name='Tip storitve'),
        ),
    ]
