# Generated by Django 5.2.1 on 2026-02-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0062_tokensettings_payment_tokens_added_to_wallet_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='custom_buy_url',
            field=models.CharField(blank=True, help_text='If set, user will be redirected to this URL to complete the purchase', max_length=256, null=True),
        ),
    ]
