# Generated by Django 5.2.1 on 2026-02-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0063_plan_custom_buy_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenSettings',
        ),
        migrations.AddField(
            model_name='plan',
            name='is_token_only',
            field=models.BooleanField(default=False, help_text='Is this plan only for purchasing tokens without any subscription or workshop included?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_purchase_quantity',
            field=models.IntegerField(blank=True, help_text='Max number of this plan a user can purchase. Only applicable for non-subscription plans.', null=True),
        ),
    ]
