# Generated by Django 5.2.1 on 2026-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0064_delete_tokensettings_plan_is_token_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='prima_group_id',
            field=models.CharField(blank=True, help_text='Prima subscription group id associated with this plan', max_length=10, null=True),
        ),
    ]
